var parties = ["새누리당", "더불어민주당", "국민의당", "정의당", "무소속"];
var members = [{
    id: 0,
    name: "강길부",
    party: 0,
    borough: "울산 울주군",
    dong: "두동면, 두서면, 범서읍, 삼남면, 삼동면, 상북면, 서생면, 언양읍, 온산읍, 온양읍, 웅촌면, 청량면",
    place: "의원회관606호",
    phone: "02-788-2708",
    email: "shinmut@assembly.go.kr",
    blog: "uljukang.org",
    twitter: "twitter.com/uljukang",
    facebook: "facebook.com/ghilboo.kang"
}, {
    id: 1,
    name: "강병원",
    party: 1,
    borough: "서울 은평구을",
    dong: "갈현제1동, 갈현제2동, 구산동, 대조동, 불광제1동, 불광제2동, 진관동",
    place: "",
    phone: "02-784-1422",
    email: "kangbw89@gmail.com",
    blog: "blog.naver.com/kangbw89",
    twitter: "twitter.com/kbw89",
    facebook: "facebook.com/kbw89"
}, {
    id: 2,
    name: "강석진",
    party: 0,
    borough: "경남 거창군 산청군 함양군 합천군",
    dong: "가북면, 가야면, 가조면, 가회면, 거창읍, 고제면, 금서면, 남상면, 남하면, 단성면, 대병면, 대양면, 덕곡면, 마리면, 마천면, 묘산면, 백전면, 병곡면, 봉산면, 북상면, 산청읍, 삼가면, 삼장면, 생비량면, 생초면, 서상면, 서하면, 수동면, 시천면, 신등면, 신안면, 신원면, 쌍백면, 쌍책면, 안의면, 야로면, 오부면, 용주면, 웅양면, 위천면, 유림면, 율곡면, 적중면, 주상면, 지곡면, 차황면, 청덕면, 초계면, 함양읍, 합천읍, 휴천면",
    place: "의원회관542호",
    phone: "02-784-1460",
    email: "ksjv7900@naver.com",
    blog: "",
    twitter: "",
    facebook: "facebook.com/kksj7900"
}, {
    id: 3,
    name: "강석호",
    party: 0,
    borough: "경북 봉화군 영덕군 영양군  울진군",
    dong: "강구면, 근남면, 금강송면, 기성면, 남정면, 달산면, 매화면, 명호면, 물야면, 법전면, 병곡면, 봉성면, 봉화읍, 북면, 상운면, 석보면, 석포면, 소천면, 수비면, 영덕읍, 영양읍, 영해면, 온정면, 울진읍, 일월면, 입암면, 재산면, 죽변면, 지품면, 창수면, 청기면, 축산면, 춘양면, 평해읍, 후포면",
    place: "의원회관707호",
    phone: "02-784-2376",
    email: "kangsh@na.go.kr",
    blog: "kangsh.kr",
    twitter: "",
    facebook: "facebook.com/kangsh314"
}, {
    id: 4,
    name: "강창일",
    party: 1,
    borough: "제주 제주시갑",
    dong: "노형동, 도두동, 삼도1동, 삼도2동, 애월읍, 연동, 오라동, 외도동, 용담1동, 용담2동, 이호동, 추자면, 한경면, 한림읍",
    place: "",
    phone: "02-784-6084",
    email: "kang809@gmail.com",
    blog: "kangci.net",
    twitter: "twitter.com/kangci52",
    facebook: "facebook.com/kangci52"
}, {
    id: 5,
    name: "강효상",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관418호",
    phone: "02-784-6195",
    email: "7882347@naver.com",
    blog: "khsstory.com/",
    twitter: "",
    facebook: ""
}, {
    id: 6,
    name: "강훈식",
    party: 1,
    borough: "충남 아산시을",
    dong: "둔포면, 배방읍, 송악면, 염치읍, 영인면, 음봉면, 인주면, 탕정면",
    place: "",
    phone: "02-784-1045",
    email: "kanghunsik@naver.com",
    blog: "blog.naver.com/kanghunsik",
    twitter: "",
    facebook: "facebook.com/gohoonsik"
}, {
    id: 7,
    name: "경대수",
    party: 0,
    borough: "충북 음성군 증평군 진천군 ",
    dong: "감곡면, 광혜원면, 금왕읍, 대소면, 덕산면, 도안면, 맹동면, 문백면, 백곡면, 삼성면, 생극면, 소이면, 원남면, 음성읍, 이월면, 증평읍, 진천읍, 초평면",
    place: "의원회관941호",
    phone: "02-784-3977",
    email: "kyungds@na.go.kr",
    blog: "kyungdaesoo.or.kr",
    twitter: "twitter.com/kyungds79",
    facebook: "facebook.com/kyungds79"
}, {
    id: 8,
    name: "고용진",
    party: 1,
    borough: "서울 노원구갑",
    dong: "공릉1동, 공릉2동, 월계1동, 월계2동, 월계3동",
    place: "",
    phone: "02-784-4840",
    email: "gogoyongjin@naver.com",
    blog: "blog.naver.com/kohyj64",
    twitter: "twitter.com/yongjin_koh",
    facebook: "facebook.com/yongjin.koh"
}, {
    id: 9,
    name: "곽대훈",
    party: 0,
    borough: "대구 달서구갑",
    dong: "신당동, 용산1동, 용산2동, 이곡1동, 이곡2동, 장기동, 죽전동",
    place: "의원회관530호",
    phone: "02-784-0790",
    email: "dhkwak605@naver.com",
    blog: "blog.naver.com/dhkwak605",
    twitter: "",
    facebook: "facebook.com/kwak605"
}, {
    id: 10,
    name: "곽상도",
    party: 0,
    borough: "대구 남구 중구",
    dong: "남산1동, 남산2동, 남산3동, 남산4동, 대명10동, 대명11동, 대명1동, 대명2동, 대명3동, 대명4동, 대명5동, 대명6동, 대명9동, 대봉1동, 대봉2동, 대신동, 동인동, 봉덕1동, 봉덕2동, 봉덕3동, 삼덕동, 성내1동, 성내2동, 성내3동, 이천동",
    place: "의원회관1014호",
    phone: "02-784-8450",
    email: "sangdokwak@na.go.kr",
    blog: "blog.naver.com/sangdokwak",
    twitter: "twitter.com/sangdokwak",
    facebook: "facebook.com/sangdokwak"
}, {
    id: 11,
    name: "권미혁",
    party: 1,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-7727",
    email: "kwonmh@na.go.kr",
    blog: "blog.naver.com/kwonmh931",
    twitter: "",
    facebook: ""
}, {
    id: 12,
    name: "권석창",
    party: 0,
    borough: "충북 제천시 단양군",
    dong: "가곡면, 교동, 금성면, 남현동, 단성면, 단양읍, 대강면, 덕산면, 매포읍, 백운면, 봉양읍, 송학면, 수산면, 신백동, 어상천면, 영서동, 영춘면, 용두동, 의암동, 인성동, 적성면, 청전동, 청풍면, 한수면, 화산동",
    place: "의원회관435호",
    phone: "02-784-0905",
    email: "sokchangk@naver.com",
    blog: "sokchang.co.kr",
    twitter: "",
    facebook: "facebook.com/sokchangk"
}, {
    id: 13,
    name: "권성동",
    party: 0,
    borough: "강원 강릉시",
    dong: "강남동, 강동면, 경포동, 교1동, 교2동, 구정면, 내곡동, 사천면, 성덕동, 성산면, 송정동, 연곡면, 옥계면, 옥천동, 왕산면, 주문진읍, 중앙동, 초당동, 포남1동, 포남2동, 홍제동",
    place: "의원회관820호",
    phone: "02-784-3396",
    email: "ksdd22@naver.com",
    blog: "ksdd.net",
    twitter: "twitter.com/ksdd22",
    facebook: "facebook.com/ksdd22"
}, {
    id: 14,
    name: "권은희",
    party: 2,
    borough: "광주 광산구을",
    dong: "비아동, 수완동, 신가동, 신창동, 임곡동, 첨단1동, 첨단2동, 하남동",
    place: "",
    phone: "02-784-1813",
    email: "kwoneunhee0215@gmail.com",
    blog: "keh.kr",
    twitter: "twitter.com/kwoneunhee0215",
    facebook: "facebook.com/kwoneh0215"
}, {
    id: 15,
    name: "권칠승",
    party: 1,
    borough: "경기 화성시병",
    dong: "기배동, 반월동, 병점1동, 병점2동, 봉담읍, 진안동, 화산동",
    place: "",
    phone: "02-784-1250",
    email: "k7wins@naver.com",
    blog: "blog.naver.com/k7wins",
    twitter: "twitter.com/k7win_",
    facebook: "facebook.com/k7win"
}, {
    id: 16,
    name: "금태섭",
    party: 1,
    borough: "서울 강서구갑",
    dong: "발산제1동, 우장산동, 화곡제1동, 화곡제2동, 화곡제3동, 화곡제8동",
    place: "",
    phone: "02-784-9761",
    email: "gsgold2001@gmail.com",
    blog: "gsgold.kr",
    twitter: "twitter.com/gtaeboy",
    facebook: "facebook.com/tae.s.keum"
}, {
    id: 17,
    name: "기동민",
    party: 1,
    borough: "서울 성북구을",
    dong: "길음제2동, 돈암제1동, 석관동, 월곡제1동, 월곡제2동, 장위제1동, 장위제2동, 장위제3동, 종암동",
    place: "",
    phone: "02-784-3181",
    email: "gidongmin@naver.com",
    blog: "blog.naver.com/gidongmin",
    twitter: "",
    facebook: "facebook.com/dongmin.gi"
}, {
    id: 18,
    name: "김경수",
    party: 1,
    borough: "경남 김해시을",
    dong: "내외동, 장유1동, 장유2동, 장유3동, 주촌면, 진례면, 칠산서부동",
    place: "",
    phone: "02-784-5871",
    email: "opensky86@naver.com",
    blog: "blog.naver.com/opensky86",
    twitter: "twitter.com/opensky86",
    facebook: "facebook.com/opensky86"
}, {
    id: 19,
    name: "김경진",
    party: 2,
    borough: "광주 북구갑",
    dong: "두암1동, 두암2동, 두암3동, 문화동, 문흥1동, 문흥2동, 석곡동, 신안동, 오치1동, 오치2동, 우산동, 임동, 중앙동, 중흥1동, 중흥2동, 중흥3동, 풍향동",
    place: "",
    phone: "02-784-2601",
    email: "2016kimkj@gmail.com",
    blog: "kimklan88.blog.me/",
    twitter: "twitter.com/kimkj008",
    facebook: "facebook.com/goodmankimkj"
}, {
    id: 20,
    name: "김경협",
    party: 1,
    borough: "경기 부천시 원미구갑",
    dong: "도당동, 소사동, 심곡1동, 심곡2동, 심곡3동, 역곡1동, 역곡2동, 원미1동, 원미2동, 춘의동",
    place: "",
    phone: "02-784-1190",
    email: "ggh000@naver.com",
    blog: "kimgh.com",
    twitter: "twitter.com/kimghkr",
    facebook: "facebook.com/kimgyunghyub"
}, {
    id: 21,
    name: "김관영",
    party: 2,
    borough: "전북 군산시",
    dong: "개정동, 개정면, 경암동, 구암동, 나운1동, 나운2동, 나운3동, 나포면, 대야면, 미성동, 삼학동, 서수면, 성산면, 소룡동, 수송동, 신풍동, 옥구읍, 옥도면, 옥산면, 옥서면, 월명동, 임피면, 조촌동, 중앙동, 해신동, 회현면, 흥남동",
    place: "",
    phone: "02-784-1781",
    email: "kky672@hanmail.net",
    blog: "usekky.com",
    twitter: "twitter.com/usekky",
    facebook: "facebook.com/usekky"
}, {
    id: 22,
    name: "김광림",
    party: 0,
    borough: "경북 안동시",
    dong: "강남동, 길안면, 남선면, 남후면, 녹전면, 도산면, 명륜동, 북후면, 서구동, 서후면, 송하동, 안기동, 예안면, 옥동, 와룡면, 용상동, 일직면, 임동면, 임하면, 중구동, 태화동, 평화동, 풍산읍, 풍천면",
    place: "의원회관944호",
    phone: "02-784-3063",
    email: "glkim@na.go.kr",
    blog: "i333.co.kr",
    twitter: "twitter.com/glkim333",
    facebook: "facebook.com/glkim333"
}, {
    id: 23,
    name: "김광수",
    party: 2,
    borough: "전북 전주시갑",
    dong: "노송동, 동서학동, 서서학동, 완산동, 인후3동, 중앙동, 중화산1동, 중화산2동, 평화1동, 평화2동, 풍남동",
    place: "",
    phone: "02-784-5970",
    email: "ks-1958@naver.com",
    blog: "blog.naver.com/ks-1958",
    twitter: "twitter.com/ks_1958",
    facebook: "facebook.com/profile.php?id=100003212864448"
}, {
    id: 24,
    name: "김규환",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관1017호",
    phone: "02-784-5680",
    email: "gyuhwan01@hanmail.net",
    blog: "",
    twitter: "",
    facebook: ""
}, {
    id: 25,
    name: "김기선",
    party: 0,
    borough: "강원 원주시갑",
    dong: "귀래면, 단계동, 무실동, 문막읍, 부론면, 우산동, 원인동, 일산동, 중앙동, 지정면, 태장1동, 태장2동, 학성동, 호저면",
    place: "의원회관410호",
    phone: "02-784-1511",
    email: "kksun290@naver.com",
    blog: "",
    twitter: "twitter.com/gambakim",
    facebook: "facebook.com/kksun290"
}, {
    id: 26,
    name: "김도읍",
    party: 0,
    borough: "부산 북구 강서구을",
    dong: "가덕도동, 가락동, 강동동, 금곡동, 녹산동, 대저1동, 대저2동, 명지동, 화명제1동, 화명제2동, 화명제3동",
    place: "의원회관408호",
    phone: "02-784-1740",
    email: "ldek3525@naver.com",
    blog: "김도읍.com",
    twitter: "twitter.com/ldek3525",
    facebook: "facebook.com/ldek3525"
}, {
    id: 27,
    name: "김동철",
    party: 2,
    borough: "광주 광산구갑",
    dong: "도산동, 동곡동, 본량동, 삼도동, 송정1동, 송정2동, 신흥동, 어룡동, 우산동, 운남동, 월곡1동, 월곡2동, 평동",
    place: "",
    phone: "02-788-2695",
    email: "kdc2000@na.go.kr",
    blog: "kdc2000.com",
    twitter: "twitter.com/kdc2000",
    facebook: "facebook.com/kdc2000"
}, {
    id: 28,
    name: "김두관",
    party: 1,
    borough: "경기 김포시갑",
    dong: "고촌읍, 김포1동, 사우동, 장기동, 풍무동",
    place: "",
    phone: "02-784-2566",
    email: "kikdok@naver.com",
    blog: "okdk.kr",
    twitter: "twitter.com/dookwan",
    facebook: "facebook.com/dreamkorea2012"
}, {
    id: 29,
    name: "김명연",
    party: 0,
    borough: "경기 안산시 단원구갑",
    dong: "선부1동, 선부2동, 선부3동, 와동, 원곡1동, 원곡2동, 원곡본동",
    place: "의원회관805호",
    phone: "02-784-1797",
    email: "my733@hanmail.net",
    blog: "vitamin21.or.kr",
    twitter: "twitter.com/mmy523400",
    facebook: ""
}, {
    id: 30,
    name: "김무성",
    party: 0,
    borough: "부산 영도구 중구",
    dong: "광복동, 남포동, 대청동, 동광동, 보수동, 부평동, 영주제1동, 영주제2동, 중앙동",
    place: "의원회관706호",
    phone: "02-784-5274",
    email: "moosung4u@naver.com",
    blog: "mskim.co.kr",
    twitter: "twitter.com/kimmoosung",
    facebook: "facebook.com/moosung4u"
}, {
    id: 31,
    name: "김민기",
    party: 1,
    borough: "경기 용인시을",
    dong: "구갈동, 기흥동, 상갈동, 상하동, 서농동, 신갈동, 영덕동",
    place: "",
    phone: "02-784-1930",
    email: "kimminki@assembly.go.kr",
    blog: "kimminki.co.kr",
    twitter: "twitter.com/kimminki84",
    facebook: "facebook.com/kminki84"
}, {
    id: 32,
    name: "김병관",
    party: 1,
    borough: "경기 성남시 분당구갑",
    dong: "백현동, 삼평동, 서현1동, 서현2동, 야탑1동, 야탑2동, 야탑3동, 운중동, 이매1동, 이매2동, 판교동",
    place: "",
    phone: "02-784-5490",
    email: "kbgbundang@gmail.com",
    blog: "blog.naver.com/bgkim",
    twitter: "twitter.com/bgkimjhs",
    facebook: "facebook.com/byounggwan"
}, {
    id: 33,
    name: "김병기",
    party: 1,
    borough: "서울 동작구갑",
    dong: "노량진제1동, 노량진제2동, 대방동, 상도제2동, 상도제3동, 상도제4동, 신대방제1동, 신대방제2동",
    place: "",
    phone: "02-784-1322",
    email: "kim-weapon@naver.com",
    blog: "kimbyungkee.kr/",
    twitter: "twitter.com/thekimweapon",
    facebook: "facebook.com/the.kim.weapon"
}, {
    id: 34,
    name: "김병욱",
    party: 1,
    borough: "경기 성남시 분당구을",
    dong: "구미1동, 구미동, 금곡동, 분당동, 수내1동, 수내2동, 수내3동, 정자1동, 정자2동, 정자3동, 정자동",
    place: "",
    phone: "02-784-3670",
    email: "777byung@naver.com",
    blog: "blog.naver.com/777byung",
    twitter: "twitter.com/777byung1",
    facebook: "facebook.com/777byung"
}, {
    id: 35,
    name: "김부겸",
    party: 1,
    borough: "대구 수성구갑",
    dong: "고산1동, 고산2동, 고산3동, 만촌1동, 만촌2동, 만촌3동, 범어1동, 범어2동, 범어3동, 범어4동, 황금1동, 황금2동",
    place: "",
    phone: "02-784-4367",
    email: "kimbookyum@naver.com",
    blog: "hopekbk.or.kr/xe/",
    twitter: "twitter.com/hopekbk",
    facebook: "facebook.com/kimbookyum"
}, {
    id: 36,
    name: "김삼화",
    party: 2,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-8231",
    email: "3flowers20@naver.com",
    blog: "blog.naver.com/3flowers20",
    twitter: "",
    facebook: "facebook.com/kimshlaw"
}, {
    id: 37,
    name: "김상훈",
    party: 0,
    borough: "대구 서구",
    dong: "내당1동, 내당2·3동, 내당4동, 비산1동, 비산2·3동, 비산4동, 비산5동, 비산6동, 비산7동, 상중이동, 원대동, 평리1동, 평리2동, 평리3동, 평리4동, 평리5동, 평리6동",
    place: "의원회관541호",
    phone: "02-784-2310",
    email: "kshdg11@gmail.com",
    blog: "kimsh.or.kr",
    twitter: "",
    facebook: "facebook.com/kshdg11"
}, {
    id: 38,
    name: "김상희",
    party: 1,
    borough: "경기 부천시 소사구",
    dong: "괴안동, 범박동, 소사본3동, 소사본동, 송내1동, 송내2동, 심곡본1동, 심곡본동, 역곡3동",
    place: "",
    phone: "02-784-4173",
    email: "shk@assembly.go.kr",
    blog: "cleankim.kr/",
    twitter: "twitter.com/SosaKim",
    facebook: "facebook.com/sosakim407"
}, {
    id: 39,
    name: "김석기",
    party: 0,
    borough: "경북 경주시",
    dong: "감포읍, 강동면, 건천읍, 내남면, 동천동, 보덕동, 불국동, 산내면, 서면, 선도동, 성건동, 안강읍, 양남면, 양북면, 외동읍, 용강동, 월성동, 중부동, 천북면, 현곡면, 황남동, 황성동, 황오동",
    place: "의원회관1010호",
    phone: "02-784-4170",
    email: "7882576kj@hanmail.net",
    blog: "blog.naver.com/podoriksk",
    twitter: "facebook.com/podoripapa",
    facebook: "facebook.com/podoripapa"
}, {
    id: 40,
    name: "김선동",
    party: 0,
    borough: "서울 도봉구을",
    dong: "도봉1동, 도봉2동, 방학1동, 방학2동, 방학3동, 쌍문2동, 쌍문4동",
    place: "의원회관626호",
    phone: "02-784-8971",
    email: "likecorea@naver.com",
    blog: "kimseondong.com",
    twitter: "twitter.com/kim_seondong",
    facebook: "facebook.com/1kimseondong"
}, {
    id: 41,
    name: "김성수",
    party: 1,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-8780",
    email: "kss_0909@naver.com",
    blog: "blog.naver.com/kss_0909",
    twitter: "",
    facebook: ""
}, {
    id: 42,
    name: "김성식",
    party: 2,
    borough: "서울 관악구갑",
    dong: "낙성대동, 남현동, 보라매동, 성현동, 신림동, 은천동, 인헌동, 중앙동, 청룡동, 청림동, 행운동",
    place: "",
    phone: "02-784-2051",
    email: "2016kimss@gmail.com",
    blog: "okkimss.com",
    twitter: "twitter.com/okkimss",
    facebook: "facebook.com/okkimss"
}, {
    id: 43,
    name: "김성원",
    party: 0,
    borough: "경기 동두천시 연천군",
    dong: "보산동, 불현동, 상패동, 생연1동, 생연2동, 소요동, 송내동, 중앙동",
    place: "의원회관911호",
    phone: "02-784-6566",
    email: "ksw-911@naver.com",
    blog: "blog.naver.com/v0413ksw",
    twitter: "twitter.com/sungwon3379",
    facebook: "facebook.com/sungwon3379"
}, {
    id: 44,
    name: "김성찬",
    party: 0,
    borough: "경남 창원시 진해구",
    dong: "경화동, 덕산동, 병암동, 석동, 여좌동, 웅동1동, 웅동2동, 웅천동, 이동, 자은동, 중앙동, 충무동, 태백동, 태평동, 풍호동",
    place: "의원회관421호",
    phone: "02-784-2477",
    email: "ksc2385@naver.com",
    blog: "blog.naver.com/ksc2385",
    twitter: "",
    facebook: "facebook.com/ksc2385"
}, {
    id: 45,
    name: "김성태",
    party: 0,
    borough: "서울 강서구을",
    dong: "가양제1동, 가양제2동, 공항동, 등촌제3동, 방화제1동, 방화제2동, 방화제3동",
    place: "의원회관910호",
    phone: "02-788-2309",
    email: "kst0331@assembly.go.kr",
    blog: "winkst.org",
    twitter: "twitter.com/kimsungtae",
    facebook: "facebook.com/winkst"
}, {
    id: 46,
    name: "김성태",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관540호",
    phone: "02-784-6651",
    email: "smart_kimst@naver.com",
    blog: "blog.naver.com/smart_kimst",
    twitter: "",
    facebook: "facebook.com/seangtae.kim"
}, {
    id: 47,
    name: "김세연",
    party: 0,
    borough: "부산 금정구",
    dong: "구서제1동, 구서제2동, 금사동, 금성동, 남산동, 부곡제1동, 부곡제2동, 부곡제3동, 부곡제4동, 서제1동, 서제2동, 서제3동, 선두구동, 장전제1동, 장전제2동, 장전제3동, 청룡노포동",
    place: "",
    phone: "02-788-2839",
    email: "kim.se.yeon@na.go.kr",
    blog: "ksy.or.kr",
    twitter: "twitter.com/seyeonkim72",
    facebook: ""
}, {
    id: 48,
    name: "김수민",
    party: 2,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-1534",
    email: "brandsumin@suminkim.net",
    blog: "suminkim.net/",
    twitter: "",
    facebook: "facebook.com/sumin.kim.3532"
}, {
    id: 49,
    name: "김순례",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관327호",
    phone: "02-784-2890",
    email: "ksrye6259@gmail.com",
    blog: "blog.naver.com/ksrye6259",
    twitter: "",
    facebook: ""
}, {
    id: 50,
    name: "김승희",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관638호",
    phone: "02-784-8191",
    email: "shkim2756@naver.com",
    blog: "blog.naver.com/shkim2756",
    twitter: "",
    facebook: "facebook.com/biokimshee"
}, {
    id: 51,
    name: "김영우",
    party: 0,
    borough: "경기 포천시 가평군",
    dong: "가산면, 관인면, 군내면, 내촌면, 선단동, 소흘읍, 신북면, 영북면, 영중면, 이동면, 일동면, 창수면, 포천동, 화현면",
    place: "",
    phone: "02-788-2014",
    email: "yw2014@naver.com",
    blog: "blog.naver.com/yw2014",
    twitter: "twitter.com/kim_youngwoo",
    facebook: "facebook.com/ywkim1"
}, {
    id: 52,
    name: "김영주",
    party: 1,
    borough: "서울 영등포구갑",
    dong: "당산제1동, 당산제2동, 도림동, 문래동, 신길제3동, 양평제1동, 양평제2동, 영등포동, 영등포본동",
    place: "",
    phone: "02-784-2470",
    email: "joojoo2012@naver.com",
    blog: "youngjoo.kr",
    twitter: "twitter.com/yjkim550727",
    facebook: "facebook.com/youngjoo2012"
}, {
    id: 53,
    name: "김영진",
    party: 1,
    borough: "경기 수원시병",
    dong: "고등동, 매교동, 매산동, 우만1동, 우만2동, 인계동, 지동, 행궁동, 화서1동, 화서2동",
    place: "",
    phone: "02-784-8410",
    email: "ersd34@naver.com",
    blog: "blog.naver.com/ersd34",
    twitter: "twitter.com/minjoop",
    facebook: "facebook.com/yjkimk"
}, {
    id: 54,
    name: "김영춘",
    party: 1,
    borough: "부산 부산진구갑",
    dong: "당감제1동, 당감제2동, 당감제4동, 부암제1동, 부암제3동, 부전제1동, 양정제1동, 양정제2동, 연지동, 초읍동",
    place: "",
    phone: "02-784-1368",
    email: "assemblyc@daum.net",
    blog: "yckim.or.kr",
    twitter: "twitter.com/busanyc",
    facebook: "facebook.com/busanyc"
}, {
    id: 55,
    name: "김영호",
    party: 1,
    borough: "서울 서대문구을",
    dong: "남가좌제1동, 남가좌제2동, 북가좌제1동, 북가좌제2동, 홍은제1동, 홍은제2동, 홍제제3동",
    place: "",
    phone: "02-784-4020",
    email: "kim-youngho@naver.com",
    blog: "blog.naver.com/frencisco",
    twitter: "twitter.com/minjoo05",
    facebook: "facebook.com/stookim"
}, {
    id: 56,
    name: "김용태",
    party: 4,
    borough: "서울 양천구을",
    dong: "신월1동, 신월2동, 신월3동, 신월4동, 신월5동, 신월6동, 신월7동, 신정3동, 신정4동",
    place: "",
    phone: "02-784-5076",
    email: "YTN@assembly.go.kr",
    blog: "YTNetwork.or.kr",
    twitter: "twitter.com/ytnetwork",
    facebook: "facebook.com/ytnetwork"
}, {
    id: 57,
    name: "김재경",
    party: 0,
    borough: "경남 진주시을",
    dong: "금산면, 대곡면, 미천면, 사봉면, 상대1동, 상대2동, 상봉동, 상평동, 이반성면, 일반성면, 중앙동, 지수면, 진성면, 집현면, 초장동, 하대1동, 하대2동",
    place: "의원회관1008호",
    phone: "02-784-0054",
    email: "kjg7942@jinjucity.com",
    blog: "youngjinju.co.kr",
    twitter: "twitter.com/powerjinju",
    facebook: ""
}, {
    id: 58,
    name: "김정우",
    party: 1,
    borough: "경기 군포시갑",
    dong: "군포1동, 군포2동, 금정동, 대야동, 산본1동",
    place: "",
    phone: "02-784-2417",
    email: "withgunpo@gmail.com",
    blog: "gunpokcw.blog.me",
    twitter: "twitter.com/bravokorea00",
    facebook: "facebook.com/bravokorea"
}, {
    id: 59,
    name: "김정재",
    party: 0,
    borough: "경북 포항시 북구",
    dong: "기계면, 기북면, 두호동, 송라면, 신광면, 양학동, 용흥동, 우창동, 장량동, 죽도동, 죽장면, 중앙동, 청하면, 환여동, 흥해읍",
    place: "의원회관909호",
    phone: "02-784-6831",
    email: "lawjj@naver.com",
    blog: "blog.naver.com/lawjj",
    twitter: "",
    facebook: "facebook.com/lawjj2016"
}, {
    id: 60,
    name: "김정훈",
    party: 0,
    borough: "부산 남구갑",
    dong: "대연제1동, 대연제3동, 대연제4동, 대연제5동, 대연제6동, 문현제1동, 문현제2동, 문현제3동, 문현제4동",
    place: "의원회관716호",
    phone: "02-784-0680",
    email: "kjh302@assembly.go.kr",
    blog: "namgu21.com",
    twitter: "twitter.com/kjh8007",
    facebook: "facebook.com/kjh8007"
}, {
    id: 61,
    name: "김종대",
    party: 3,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-7612",
    email: "jdkim549@gmail.com",
    blog: "blog.naver.com/jdkim549",
    twitter: "",
    facebook: "facebook.com/jdkim.justice"
}, {
    id: 62,
    name: "김종민",
    party: 1,
    borough: "충남 논산시 계룡시 금산군",
    dong: "군북면, 금산읍, 금성면, 남이면, 남일면, 복수면, 부리면, 제원면, 진산면, 추부면",
    place: "",
    phone: "02-784-5920",
    email: "socmind@naver.com",
    blog: "blog.naver.com/socmind",
    twitter: "twitter.com/socmind",
    facebook: "facebook.com/socmind"
}, {
    id: 63,
    name: "김종석",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관320호",
    phone: "02-784-6430",
    email: "jskim@na.go.kr",
    blog: "kimjongseok.com/",
    twitter: "",
    facebook: "facebook.com/jongseok1"
}, {
    id: 64,
    name: "김종인",
    party: 1,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-8870",
    email: "kimci404@naver.com",
    blog: "kimchongin.com/",
    twitter: "",
    facebook: ""
}, {
    id: 65,
    name: "김종태",
    party: 0,
    borough: "경북 상주시 군위군 의성군 청송군",
    dong: "가음면, 계림동, 고로면, 공검면, 공성면, 구천면, 군위읍, 금성면, 낙동면, 남원동, 내서면, 다인면, 단밀면, 단북면, 단촌면, 동문동, 동성동, 모동면, 모서면, 봉양면, 부계면, 부남면, 부동면, 북문동, 비안면, 사곡면, 사벌면, 산성면, 소보면, 신평면, 신흥동, 안계면, 안덕면, 안사면, 안평면, 옥산면, 외남면, 외서면, 우보면, 은척면, 의성읍, 의흥면, 이안면, 점곡면, 중동면, 진보면, 청리면, 청송읍, 춘산면, 파천면, 함창읍, 현동면, 현서면, 화남면, 화동면, 화북면, 화서면, 효령면",
    place: "의원회관452호",
    phone: "02-784-3190",
    email: "kimjt2012@na.go.kr",
    blog: "kjt3600.kr",
    twitter: "twitter.com/kjt3600",
    facebook: "facebook.com/kjt3600"
}, {
    id: 66,
    name: "김종회",
    party: 3,
    borough: "전북 김제시 부안군",
    dong: "검산동, 계화면, 공덕면, 광활면, 교월동, 금구면, 금산면, 동진면, 만경읍, 백구면, 백산면, 백산면, 변산면, 보안면, 봉남면, 부량면, 부안읍, 상서면, 성덕면, 신풍동, 요촌동, 용지면, 위도면, 주산면, 죽산면, 줄포면, 진봉면, 진서면, 청하면, 하서면, 행안면, 황산면",
    place: "",
    phone: "02-784-2704",
    email: "weemin21@naver.com",
    blog: "blog.naver.com/weemin21",
    twitter: "twitter.com/weemin21",
    facebook: "facebook.com/KimJonghoi"
}, {
    id: 67,
    name: "김종훈",
    party: 4,
    borough: "울산 동구",
    dong: "남목1동, 남목2동, 남목3동, 대송동, 방어동, 일산동, 전하1동, 전하2동, 화정동",
    place: "",
    phone: "02-784-9630",
    email: "donggulove745@gmail.com",
    blog: "facebook.com/donggulove1234",
    twitter: "",
    facebook: "facebook.com/donggulove"
}, {
    id: 68,
    name: "김중로",
    party: 2,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-9160",
    email: "kjroffice@naver.com",
    blog: "blog.naver.com/kjroffice",
    twitter: "",
    facebook: "facebook.com/joongrokim"
}, {
    id: 69,
    name: "김진태",
    party: 0,
    borough: "강원 춘천시",
    dong: "강남동, 교동, 근화동, 남면, 남산면, 동내면, 동면, 동산면, 북산면, 사북면, 서면, 석사동, 소양동, 신동면, 신북읍, 신사우동, 약사명동, 조운동, 퇴계동, 효자1동, 효자2동, 효자3동, 후평1동, 후평2동, 후평3동",
    place: "의원회관437호",
    phone: "02-784-3760",
    email: "jtkim1013@na.go.kr",
    blog: "kimjintae.co.kr/",
    twitter: "twitter.com/jtkim1013",
    facebook: "facebook.com/jtkim1013"
}, {
    id: 70,
    name: "김진표",
    party: 1,
    borough: "경기 수원시무",
    dong: "곡선동, 권선1동, 권선2동, 세류1동, 세류2동, 세류3동, 영통2동, 태장동",
    place: "",
    phone: "02-784-3807",
    email: "jinpyo311@naver.com",
    blog: "blog.naver.com/jinpyo311",
    twitter: "twitter.com/jinpyokim",
    facebook: "facebook.com/jinpyowa"
}, {
    id: 71,
    name: "김철민",
    party: 1,
    borough: "경기 안산시 상록구을",
    dong: "부곡동, 성포동, 안산동, 월피동, 이동, 일동",
    place: "",
    phone: "02-784-2135",
    email: "kcm8764@naver.com",
    blog: "blog.naver.com/kcm8764",
    twitter: "twitter.com/kimcm8764",
    facebook: "facebook.com/kcm8764"
}, {
    id: 72,
    name: "김태년",
    party: 1,
    borough: "경기 성남시 수정구",
    dong: "고등동, 단대동, 복정동, 산성동, 수진1동, 수진2동, 시흥동, 신촌동, 신흥1동, 신흥2동, 신흥3동, 양지동, 위례동, 태평1동, 태평2동, 태평3동, 태평4동",
    place: "",
    phone: "02-784-4570",
    email: "ktn0320@daum.net",
    blog: "ktn21.com",
    twitter: "twitter.com/kimtaenyeon",
    facebook: "facebook.com/kimtaenyeon"
}, {
    id: 73,
    name: "김태흠",
    party: 0,
    borough: "충남 보령시 서천군",
    dong: "남포면, 대천1동, 대천2동, 대천3동, 대천4동, 대천5동, 미산면, 성주면, 오천면, 웅천읍, 주교면, 주산면, 주포면, 천북면, 청라면, 청소면",
    place: "의원회관407호",
    phone: "02-784-4710",
    email: "ktheum@hanmail.net",
    blog: "kimtaeheum.com",
    twitter: "twitter.com/ktheum",
    facebook: "facebook.com/ktheum"
}, {
    id: 74,
    name: "김학용",
    party: 0,
    borough: "경기 안성시",
    dong: "고삼면, 공도읍, 금광면, 대덕면, 미양면, 보개면, 삼죽면, 서운면, 안성1동, 안성2동, 안성3동, 양성면, 원곡면, 일죽면, 죽산면",
    place: "의원회관427호",
    phone: "02-784-3860",
    email: "ansung@assembly.go.kr",
    blog: "ansung365.com",
    twitter: "",
    facebook: "facebook.com/KimHackYong"
}, {
    id: 75,
    name: "김한정",
    party: 1,
    borough: "경기 남양주시을",
    dong: "별내동, 별내면, 오남읍, 진접읍",
    place: "",
    phone: "02-784-0496",
    email: "hanjkim631@naver.com",
    blog: "blog.naver.com/hanjungkim",
    twitter: "twitter.com/hanjungok",
    facebook: "facebook.com/hanjungkim21"
}, {
    id: 76,
    name: "김한표",
    party: 0,
    borough: "경남 거제시",
    dong: "거제면, 고현동, 남부면, 능포동, 동부면, 둔덕면, 마전동, 사등면, 상문동, 수양동, 아주동, 연초면, 옥포1동, 옥포2동, 일운면, 장목면, 장승포동, 장평동, 하청면",
    place: "의원회관736호",
    phone: "02-784-4760",
    email: "khpgeoje@naver.com",
    blog: "hanpyo.org",
    twitter: "twitter.com/khp1001",
    facebook: "facebook.com/khpgeoje"
}, {
    id: 77,
    name: "김해영",
    party: 1,
    borough: "부산 연제구",
    dong: "거제제1동, 거제제2동, 거제제3동, 거제제4동, 연산제1동, 연산제2동, 연산제3동, 연산제4동, 연산제5동, 연산제6동, 연산제8동, 연산제9동",
    place: "",
    phone: "02-784-1051",
    email: "hykim0417@naver.com",
    blog: "blog.naver.com/hykim0417",
    twitter: "",
    facebook: "facebook.com/hyk0417"
}, {
    id: 78,
    name: "김현권",
    party: 1,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-2841",
    email: "farmhk20@gmail.com",
    blog: "blog.daum.net/countryandcity",
    twitter: "twitter.com/hanwooabi",
    facebook: "facebook.com/hanwooabi"
}, {
    id: 79,
    name: "김현미",
    party: 1,
    borough: "경기 고양시정",
    dong: "대화동, 송산동, 송포동, 일산1동, 일산3동, 주엽1동, 주엽2동, 탄현동",
    place: "",
    phone: "02-784-4990",
    email: "7844990@naver.com",
    blog: "hyunmee.net",
    twitter: "twitter.com/hyunmeek",
    facebook: "facebook.com/hyunmeek"
}, {
    id: 80,
    name: "김현아",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관515호",
    phone: "02-784-5601",
    email: "dposhyun@naver.com",
    blog: "blog.naver.com/dposhyun",
    twitter: "",
    facebook: "facebook.com/dposhyun?fref=ts"
}, {
    id: 81,
    name: "나경원",
    party: 0,
    borough: "서울 동작구을",
    dong: "사당제1동, 사당제2동, 사당제3동, 사당제4동, 사당제5동, 상도제1동, 흑석동",
    place: "의원회관450호",
    phone: "02-784-3103",
    email: "nakw@na.go.kr",
    blog: "blog.naver.com/nakw63",
    twitter: "",
    facebook: "facebook.com/nakw1963"
}, {
    id: 82,
    name: "남인순",
    party: 1,
    borough: "서울 송파구병",
    dong: "가락2동, 가락본동, 거여1동, 거여2동, 마천1동, 마천2동, 문정1동, 오금동, 위례동, 장지동",
    place: "",
    phone: "02-784-5980",
    email: "nisoon@na.go.kr",
    blog: "nisoon.co.kr",
    twitter: "twitter.com/nisoon",
    facebook: "facebook.com/nisoon"
}, {
    id: 83,
    name: "노웅래",
    party: 1,
    borough: "서울 마포구갑",
    dong: "공덕동, 대흥동, 도화동, 신수동, 아현동, 염리동, 용강동",
    place: "",
    phone: "02-788-2203",
    email: "wraenoh@hanmail.net",
    blog: "gowithwr.com",
    twitter: "twitter.com/GoWith_WRaenoh",
    facebook: "facebook.com/gowithwrae/"
}, {
    id: 84,
    name: "노회찬",
    party: 3,
    borough: "경남 창원시 성산구",
    dong: "가음정동, 반송동, 사파동, 상남동, 성주동, 웅남동, 중앙동",
    place: "",
    phone: "02-784-9130",
    email: "omychans@naver.com",
    blog: "omychans.tistory.com/",
    twitter: "twitter.com/hcroh",
    facebook: "facebook.com/omyChans/"
}, {
    id: 85,
    name: "도종환",
    party: 1,
    borough: "충북 청주시흥덕구",
    dong: "가경동, 강내면, 강서제1동, 강서제2동, 복대제1동, 복대제2동, 봉명제1동, 봉명제2·송정동, 오송읍, 옥산면, 운천·신봉동",
    place: "",
    phone: "02-784-2537",
    email: "djhpoem@assembly.go.kr",
    blog: "djh333.co.kr",
    twitter: "twitter.com/djhpoem2",
    facebook: "facebook.com/djhpoem"
}, {
    id: 86,
    name: "문미옥",
    party: 1,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-9671",
    email: "miockmun@naver.com",
    blog: "blog.naver.com/miockmun",
    twitter: "",
    facebook: "facebook.com/munmiock"
}, {
    id: 87,
    name: "문진국",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관827호",
    phone: "02-784-9340",
    email: "kook4616@naver.com",
    blog: "blog.naver.com/kook4616",
    twitter: "",
    facebook: ""
}, {
    id: 88,
    name: "문희상",
    party: 1,
    borough: "경기 의정부시갑",
    dong: "가능1동, 가능2동, 가능3동, 녹양동, 의정부1동, 의정부2동, 의정부3동, 호원1동, 호원2동",
    place: "",
    phone: "02-784-1261",
    email: "moonhs@assembly.go.kr",
    blog: "moonhs.net",
    twitter: "twitter.com/moonhstw",
    facebook: "facebook.com/moonhsface"
}, {
    id: 89,
    name: "민경욱",
    party: 0,
    borough: "인천 연수구을",
    dong: "동춘1동, 동춘2동, 송도1동, 송도2동, 송도3동, 옥련1동",
    place: "의원회관628호",
    phone: "02-784-4071",
    email: "minkyungwook@naver.com",
    blog: "blog.naver.com/minkyungwook",
    twitter: "twitter.com/minkyungwook",
    facebook: "facebook.com/minkyungwookk"
}, {
    id: 90,
    name: "민병두",
    party: 1,
    borough: "서울 동대문구을",
    dong: "답십리제1동, 답십리제2동, 장안제1동, 장안제2동, 전농제1동, 전농제2동",
    place: "",
    phone: "02-788-2256",
    email: "bdmin1958@assembly.go.kr",
    blog: "bdmin.net",
    twitter: "twitter.com/bdmin1958",
    facebook: "facebook.com/bdmin2016"
}, {
    id: 91,
    name: "민홍철",
    party: 1,
    borough: "경남 김해시갑",
    dong: "대동면, 동상동, 부원동, 북부동, 불암동, 삼안동, 상동면, 생림면, 진영읍, 한림면, 활천동, 회현동",
    place: "",
    phone: "02-784-6490",
    email: "rediron2400@naver.com",
    blog: "민사랑.com/",
    twitter: "twitter.com/minstar21c",
    facebook: ""
}, {
    id: 92,
    name: "박경미",
    party: 1,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-6120",
    email: "parkkm321@naver.com",
    blog: "blog.naver.com/parkkm321",
    twitter: "",
    facebook: ""
}, {
    id: 93,
    name: "박광온",
    party: 1,
    borough: "경기 수원시정",
    dong: "광교1동, 광교2동, 매탄1동, 매탄2동, 매탄3동, 매탄4동, 영통1동, 원천동",
    place: "",
    phone: "02-784-5364",
    email: "sotong533@gmail.com",
    blog: "blog.naver.com/kopark2012",
    twitter: "twitter.com/parkkwangon",
    facebook: "facebook.com/mentpko"
}, {
    id: 94,
    name: "박남춘",
    party: 1,
    borough: "인천 남동구갑",
    dong: "간석1동, 간석4동, 구월1동, 구월3동, 구월4동, 남촌도림동, 논현1동, 논현2동, 논현고잔동",
    place: "",
    phone: "02-784-6181",
    email: "parknamchun@naver.com",
    blog: "blog.naver.com/parknamchun",
    twitter: "twitter.com/parknamchun",
    facebook: "facebook.com/parknamchun"
}, {
    id: 95,
    name: "박대출",
    party: 0,
    borough: "경남 진주시갑",
    dong: "가호동, 금곡면, 내동면, 대평면, 명석면, 문산읍, 성북동, 수곡면, 신안동, 이현동, 정촌면, 천전동, 충무공동, 판문동, 평거동",
    place: "의원회관802호",
    phone: "02-784-6750",
    email: "dcparkjj@assembly.go.kr",
    blog: "wejinju.co.kr",
    twitter: "twitter.com/dcparkjj",
    facebook: "facebook.com/daechul.bag"
}, {
    id: 96,
    name: "박덕흠",
    party: 0,
    borough: "충북 보은군 옥천군 영동군 괴산군",
    dong: "감물면, 괴산읍, 군북면, 군서면, 내북면, 동이면, 마로면, 매곡면, 문광면, 보은읍, 불정면, 사리면, 산외면, 삼승면, 상촌면, 소수면, 속리산면, 수한면, 심천면, 안남면, 안내면, 양강면, 양산면, 연풍면, 영동읍, 옥천읍, 용산면, 용화면, 이원면, 장안면, 장연면, 청산면, 청성면, 청안면, 청천면, 추풍령면, 칠성면, 탄부면, 학산면, 황간면, 회남면, 회인면",
    place: "의원회관604호",
    phone: "02-784-6550",
    email: "parkdukhyum@naver.com",
    blog: "parkdukhyum.blog.me/",
    twitter: "twitter.com/parkdukhyum",
    facebook: "facebook.com/parkdukhyum"
}, {
    id: 97,
    name: "박맹우",
    party: 0,
    borough: "울산 남구을",
    dong: "달동, 대현동, 삼산동, 선암동, 수암동, 야음장생포동",
    place: "의원회관416호",
    phone: "02-788-2259",
    email: "ulsanbmw1@naver.com",
    blog: "blog.naver.com/ulsanpmw",
    twitter: "",
    facebook: ""
}, {
    id: 98,
    name: "박명재",
    party: 0,
    borough: "경북 포항시 남구 울릉군",
    dong: "구룡포읍, 대송면, 대이동, 동해면, 북면, 상대동, 서면, 송도동, 연일읍, 오천읍, 울릉읍, 장기면, 제철동, 청림동, 해도동, 호미곶면, 효곡동",
    place: "의원회관619호",
    phone: "02-788-2174",
    email: "mjp@na.go.kr",
    blog: "blog.naver.com/mjpark531",
    twitter: "twitter.com/mjepark531",
    facebook: "facebook.com/mjepark531"
}, {
    id: 99,
    name: "박범계",
    party: 1,
    borough: "대전 서구을",
    dong: "갈마1동, 갈마2동, 둔산1동, 둔산2동, 둔산3동, 만년동, 용문동, 월평1동, 월평2동, 월평3동, 탄방동",
    place: "",
    phone: "02-784-6960",
    email: "bkfire1004@naver.com",
    blog: "bkfire.co.kr/",
    twitter: "twitter.com/bkfire1004",
    facebook: "facebook.com/bkfire"
}, {
    id: 100,
    name: "박병석",
    party: 1,
    borough: "대전 서구갑",
    dong: "가수원동, 가장동, 관저1동, 관저2동, 괴정동, 기성동, 내동, 도마1동, 도마2동, 변동, 복수동, 정림동",
    place: "",
    phone: "02-788-2306",
    email: "pbs21@assembly.go.kr",
    blog: "pbs21.or.kr",
    twitter: "",
    facebook: "facebook.com/pbs21"
}, {
    id: 101,
    name: "박선숙",
    party: 2,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-2390",
    email: "suns998@naver.com",
    blog: "blog.naver.com/suns998",
    twitter: "",
    facebook: ""
}, {
    id: 102,
    name: "박성중",
    party: 0,
    borough: "서울 서초구을",
    dong: "내곡동, 방배2동, 방배3동, 서초1동, 서초2동, 서초3동, 서초4동, 양재1동, 양재2동",
    place: "의원회관936호",
    phone: "02-784-4364",
    email: "sjpark101@hanmail.net",
    blog: "blog.naver.com/sjpark580801",
    twitter: "twitter.com/parksungjoong",
    facebook: "facebook.com/sjpark101"
}, {
    id: 103,
    name: "박순자",
    party: 0,
    borough: "경기 안산시 단원구을",
    dong: "고잔1동, 고잔2동, 대부동, 초지동, 호수동",
    place: "의원회관426호",
    phone: "02-784-1606",
    email: "hisoonja@assembly.go.kr",
    blog: "blog.naver.com/hisoonja3",
    twitter: "",
    facebook: "facebook.com/hisoonja"
}, {
    id: 104,
    name: "박영선",
    party: 1,
    borough: "서울 구로구을",
    dong: "가리봉동, 구로제1동, 구로제2동, 구로제3동, 구로제4동, 구로제5동, 신도림동",
    place: "",
    phone: "02-784-3870",
    email: "parkyoungsun21@gmail.com",
    blog: "blog.pys21.net",
    twitter: "twitter.com/Park_Youngsun",
    facebook: "facebook.com/Parkyoungsun21"
}, {
    id: 105,
    name: "박완수",
    party: 0,
    borough: "경남 창원시 의창구",
    dong: "대산면, 동읍, 명곡동, 봉림동, 북면, 용지동, 의창동, 팔룡동",
    place: "의원회관705호",
    phone: "02-784-7773",
    email: "wansu2u@naver.com",
    blog: "blog.naver.com/wansu2u",
    twitter: "",
    facebook: "facebook.com/wansu2u"
}, {
    id: 106,
    name: "박완주",
    party: 1,
    borough: "충남 천안시을",
    dong: "백석동, 부성1동, 부성2동, 불당동, 성거읍, 성환읍, 입장면, 직산읍",
    place: "",
    phone: "02-784-7560",
    email: "lasco21@hanmail.net",
    blog: "blog.naver.com/withwanju/",
    twitter: "twitter.com/park_wanju",
    facebook: "facebook.com/parkwanju"
}, {
    id: 107,
    name: "박용진",
    party: 1,
    borough: "서울 강북구을",
    dong: "미아동, 번제3동, 삼각산동, 삼양동, 송중동, 송천동",
    place: "",
    phone: "02-784-9721",
    email: "gangbuk24@gmail.com",
    blog: "parkyongjin.com/",
    twitter: "",
    facebook: "facebook.com/yongjin.bag"
}, {
    id: 108,
    name: "박인숙",
    party: 0,
    borough: "서울 송파구갑",
    dong: "방이1동, 방이2동, 송파1동, 송파2동, 오륜동, 잠실4동, 잠실6동, 풍납1동, 풍납2동",
    place: "의원회관915호",
    phone: "02-784-7810",
    email: "ispark0530@naver.com",
    blog: "parkinsook.co.kr",
    twitter: "",
    facebook: "facebook.com/ispark0530"
}, {
    id: 109,
    name: "박재호",
    party: 1,
    borough: "부산 남구을",
    dong: "감만제1동, 감만제2동, 용당동, 용호제1동, 용호제2동, 용호제3동, 용호제4동, 우암동",
    place: "",
    phone: "02-784-5512",
    email: "2016pjh@gmail.com",
    blog: "blog.naver.com/pjh0586",
    twitter: "twitter.com/ourpark",
    facebook: "facebook.com/parkjaeho"
}, {
    id: 110,
    name: "박정",
    party: 1,
    borough: "경기 파주시을",
    dong: "군내면, 금촌1동, 금촌2동, 금촌3동, 문산읍, 법원읍, 월롱면, 적성면, 진동면, 파주읍, 파평면",
    place: "",
    phone: "02-784-3781",
    email: "pjkorea21c@naver.com",
    blog: "blog.naver.com/pjkorea21c",
    twitter: "twitter.com/pjkorea21c",
    facebook: "facebook.com/pjkorea21c"
}, {
    id: 111,
    name: "박주민",
    party: 1,
    borough: "서울 은평구갑",
    dong: "녹번동, 수색동, 신사제1동, 신사제2동, 역촌동, 응암제1동, 응암제2동, 응암제3동, 증산동",
    place: "",
    phone: "02-784-8690",
    email: "joomincenter@gmail.com",
    blog: "joomincenter.com",
    twitter: "twitter.com/yoeman6310",
    facebook: "facebook.com/eunpyoung.joomin"
}, {
    id: 112,
    name: "박주선",
    party: 2,
    borough: "광주 동구 남구을",
    dong: "계림1동, 계림2동, 동명동, 방림1동, 방림2동, 백운1동, 백운2동, 사직동, 산수1동, 산수2동, 서남동, 양림동, 지산1동, 지산2동, 지원1동, 지원2동, 충장동, 학동, 학운동",
    place: "",
    phone: "02-784-5288",
    email: "jsp@na.go.kr",
    blog: "parkjoosun.pe.kr",
    twitter: "twitter.com/parkjoosun",
    facebook: "facebook.com/parkjoosun"
}, {
    id: 113,
    name: "박주현",
    party: 2,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-6341",
    email: "pjh0411508@gmail.com",
    blog: "blog.naver.com/parkjoohyun508",
    twitter: "",
    facebook: "facebook.com/parkjoohyun508"
}, {
    id: 114,
    name: "박준영",
    party: 2,
    borough: "전남 영암군 무안군 신안군",
    dong: "군서면, 금정면, 덕진면, 도초면, 도포면, 망운면, 몽탄면, 무안읍, 미암면, 비금면, 삼향읍, 삼호읍, 서호면, 시종면, 신북면, 신의면, 안좌면, 암태면, 압해읍, 영암읍, 운남면, 일로읍, 임자면, 자은면, 장산면, 증도면, 지도읍, 청계면, 팔금면, 하의면, 학산면, 해제면, 현경면, 흑산면",
    place: "",
    phone: "02-784-9501",
    email: "greenpark21c@naver.com",
    blog: "parkjoonyung.kr",
    twitter: "twitter.com/JYPARK615",
    facebook: "facebook.com/joonyung.park.1"
}, {
    id: 115,
    name: "박지원",
    party: 2,
    borough: "전남 목포시",
    dong: "대성동, 동명동, 만호동, 목원동, 부주동, 부흥동, 북항동, 산정동, 삼학동, 삼향동, 상동, 신흥동, 연동, 연산동, 옥암동, 용당1동, 용당2동, 용해동, 원산동, 유달동, 이로동, 죽교동, 하당동",
    place: "",
    phone: "02-784-4179",
    email: "jwp615@hanmail.net",
    blog: "jwp615.com",
    twitter: "twitter.com/jwp615",
    facebook: "facebook.com/jwp615"
}, {
    id: 116,
    name: "박찬대",
    party: 1,
    borough: "인천 연수구갑",
    dong: "동춘3동, 선학동, 연수1동, 연수2동, 연수3동, 옥련2동, 청학동",
    place: "",
    phone: "02-784-5477",
    email: "parkcd0214@gmail.com",
    blog: "blog.naver.com/starhanmia",
    twitter: "",
    facebook: "facebook.com/whiparam"
}, {
    id: 117,
    name: "박찬우",
    party: 0,
    borough: "충남 천안시갑",
    dong: "동면, 목천읍, 문성동, 병천면, 봉명동, 북면, 성남면, 성정1동, 성정2동, 수신면, 신안동, 원성1동, 원성2동, 일봉동, 중앙동",
    place: "의원회관436호",
    phone: "02-784-8540",
    email: "pcw3522@naver.com",
    blog: "blog.naver.com/pcw3522",
    twitter: "",
    facebook: "facebook.com/pcw3521"
}, {
    id: 118,
    name: "박홍근",
    party: 1,
    borough: "서울 중랑구을",
    dong: "망우본동, 묵제1동, 묵제2동, 상봉제1동, 신내제1동, 신내제2동, 중화제1동, 중화제2동",
    place: "",
    phone: "02-784-8370",
    email: "maumgil88@gmail.com",
    blog: "blog.naver.com/bakhonggeun",
    twitter: "twitter.com/maumgil",
    facebook: "facebook.com/maumgil"
}, {
    id: 119,
    name: "배덕광",
    party: 0,
    borough: "부산 해운대구을",
    dong: "반송제1동, 반송제2동, 반여제1동, 반여제2동, 반여제3동, 반여제4동, 재송제1동, 재송제2동",
    place: "의원회관1007호",
    phone: "02-784-0797",
    email: "baedk@na.go.kr",
    blog: "blog.naver.com/baedk48",
    twitter: "twitter.com/baedukkwang",
    facebook: "facebook.com/baedukkwang"
}, {
    id: 120,
    name: "백승주",
    party: 0,
    borough: "경북 구미시갑",
    dong: "공단1동, 공단2동, 광평동, 도량동, 비산동, 상모사곡동, 선주원남동, 송정동, 신평1동, 신평2동, 원평1동, 원평2동, 임오동, 지산동, 형곡1동, 형곡2동",
    place: "의원회관830호",
    phone: "02-784-6730",
    email: "gumibsj1778@naver.com",
    blog: "blog.naver.com/gumibsj1778",
    twitter: "",
    facebook: "facebook.com/gumibsj1778"
}, {
    id: 121,
    name: "백재현",
    party: 1,
    borough: "경기 광명시갑",
    dong: "광명1동, 광명2동, 광명3동, 광명4동, 광명5동, 광명6동, 광명7동, 철산1동, 철산2동, 철산4동",
    place: "",
    phone: "02-784-6396",
    email: "jhok100@hanmail.net",
    blog: "ok100.or.kr",
    twitter: "twitter.com/jhok100",
    facebook: "facebook.com/jhok100"
}, {
    id: 122,
    name: "백혜련",
    party: 1,
    borough: "경기 수원시을",
    dong: "구운동, 금곡동, 서둔동, 율천동, 입북동, 평동, 호매실동",
    place: "",
    phone: "02-784-6130",
    email: "100hyeryun@naver.com",
    blog: "blog.naver.com/100hyeryun",
    twitter: "twitter.com/100HyeRyun",
    facebook: "facebook.com/100hyeryun1"
}, {
    id: 123,
    name: "변재일",
    party: 1,
    borough: "충북 청주시 청원구",
    dong: "내덕제1동, 내덕제2동, 내수읍, 북이면, 오근장동, 오창읍, 우암동, 율량·사천동",
    place: "",
    phone: "02-784-1626",
    email: "bji@assembly.go.kr",
    blog: "open21.or.kr",
    twitter: "twitter.com/byunjaeill",
    facebook: "facebook.com/open1197"
}, {
    id: 124,
    name: "서영교",
    party: 4,
    borough: "서울 중랑구갑",
    dong: "망우제3동, 면목본동, 면목제2동, 면목제3·8동, 면목제4동, 면목제5동, 면목제7동, 상봉제2동",
    place: "",
    phone: "02-784-8490",
    email: "youngkyos@naver.com",
    blog: "blog.naver.com/youngkyos",
    twitter: "twitter.com/seoyoungkyo",
    facebook: "facebook.com/seoyoungkyos"
}, {
    id: 125,
    name: "서청원",
    party: 0,
    borough: "경기 화성시갑",
    dong: "남양읍, 마도면, 매송면, 비봉면, 서신면, 송산면, 양감면, 우정읍, 장안면, 정남면, 팔탄면, 향남읍",
    place: "의원회관601호",
    phone: "02-788-2078",
    email: "suhcw@assembly.go.kr",
    blog: "suhchungwon.com",
    twitter: "twitter.com/scw0403",
    facebook: "facebook.com/suhchungwon"
}, {
    id: 126,
    name: "서형수",
    party: 1,
    borough: "경남 양산시을",
    dong: "덕계동, 동면, 서창동, 소주동, 양주동, 평산동",
    place: "",
    phone: "02-784-1524",
    email: "shsoo2016@naver.com",
    blog: "blog.naver.com/shsoo2016",
    twitter: "twitter.com/yangsansoo",
    facebook: "facebook.com/shsyangsan"
}, {
    id: 127,
    name: "설훈",
    party: 1,
    borough: "경기 부천시 원미구을",
    dong: "상1동, 상2동, 상3동, 상동, 약대동, 중1동, 중2동, 중3동, 중4동, 중동",
    place: "",
    phone: "02-784-8570",
    email: "sulhoon21@naver.com",
    blog: "sulhoon.com",
    twitter: "twitter.com/sulhoon",
    facebook: ""
}, {
    id: 128,
    name: "성일종",
    party: 0,
    borough: "충남 서산시 태안군",
    dong: "고북면, 대산읍, 동문1동, 동문2동, 부석면, 부춘동, 석남동, 성연면, 수석동, 운산면, 음암면, 인지면, 지곡면, 팔봉면, 해미면",
    place: "의원회관423호",
    phone: "02-784-6290",
    email: "sij5140@naver.com",
    blog: "sungij.co.kr",
    twitter: "",
    facebook: "facebook.com/sij5140"
}, {
    id: 129,
    name: "소병훈",
    party: 1,
    borough: "경기 광주시갑",
    dong: "경안동, 광남동, 남종면, 남한산성면, 송정동, 퇴촌면",
    place: "",
    phone: "02-784-5020",
    email: "sotongsa@naver.com",
    blog: "blog.naver.com/sotongsa",
    twitter: "twitter.com/sotongsa",
    facebook: "facebook.com/sotongsa1"
}, {
    id: 130,
    name: "손금주",
    party: 2,
    borough: "전남 나주시 화순군",
    dong: "공산면, 금남동, 금천면, 남면, 남평읍, 노안면, 능주면, 다도면, 다시면, 도곡면, 도암면, 동강면, 동면, 동복면, 문평면, 반남면, 봉황면, 북면, 빛가람동, 산포면, 성북동, 세지면, 송월동, 영강동, 영산동, 왕곡면, 이서면, 이양면, 이창동, 청풍면, 춘양면, 한천면, 화순읍",
    place: "",
    phone: "02-784-9401",
    email: "nowjs21@naver.com",
    blog: "blog.naver.com/nowjs21",
    twitter: "twitter.com/thisweek905",
    facebook: "facebook.com/nowjs"
}, {
    id: 131,
    name: "손혜원",
    party: 1,
    borough: "서울 마포구을",
    dong: "망원1동, 망원2동, 상암동, 서강동, 서교동, 성산1동, 성산2동, 연남동, 합정동",
    place: "",
    phone: "02-784-9241",
    email: "shwmapo@naver.com",
    blog: "",
    twitter: "twitter.com/sohnhyewon",
    facebook: "facebook.com/sohnhyewon"
}, {
    id: 132,
    name: "송기석",
    party: 2,
    borough: "광주 서구갑",
    dong: "광천동, 농성1동, 농성2동, 동천동, 상무1동, 양3동, 양동, 유덕동, 치평동, 화정1동, 화정2동",
    place: "",
    phone: "02-784-5750",
    email: "gssong534@gmail.com",
    blog: "gssong8.blog.me/",
    twitter: "twitter.com/gssong7",
    facebook: "facebook.com/gssong7"
}, {
    id: 133,
    name: "송기헌",
    party: 1,
    borough: "강원 원주시을",
    dong: "개운동, 단구동, 명륜1동, 명륜2동, 반곡관설동, 봉산동, 소초면, 신림면, 판부면, 행구동, 흥업면",
    place: "",
    phone: "02-784-6150",
    email: "peacesong1@naver.com",
    blog: "peacesong1.blog.me",
    twitter: "",
    facebook: "facebook.com/withsong"
}, {
    id: 134,
    name: "송석준",
    party: 0,
    borough: "경기 이천시",
    dong: "관고동, 대월면, 마장면, 모가면, 백사면, 부발읍, 설성면, 신둔면, 율면, 장호원읍, 중리동, 증포동, 창전동, 호법면",
    place: "의원회관734호",
    phone: "02-784-3161",
    email: "icheonsarang734@assembly.co.kr",
    blog: "icheonsarang.com/",
    twitter: "",
    facebook: "facebook.com/icheonsarang"
}, {
    id: 135,
    name: "송영길",
    party: 1,
    borough: "인천 계양구을",
    dong: "계산1동, 계산2동, 계산3동, 계산4동, 계양1동, 계양2동, 계양3동",
    place: "",
    phone: "02-784-8957",
    email: "songyounggil@naver.com",
    blog: "blog.naver.com/songyounggil",
    twitter: "twitter.com/Bulloger",
    facebook: "facebook.com/SongYounggill"
}, {
    id: 136,
    name: "송옥주",
    party: 1,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-9470",
    email: "songok4740@naver.com",
    blog: "blog.naver.com/songok4740",
    twitter: "twitter.com/songokju",
    facebook: "facebook.com/okju.song.52"
}, {
    id: 137,
    name: "송희경",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관1011호",
    phone: "",
    email: "alpha-song@naver.com",
    blog: "blog.naver.com/alpha-song",
    twitter: "",
    facebook: "facebook.com/ITssong/"
}, {
    id: 138,
    name: "신경민",
    party: 1,
    borough: "서울 영등포구을",
    dong: "대림제1동, 대림제2동, 대림제3동, 신길제1동, 신길제4동, 신길제5동, 신길제6동, 신길제7동, 여의동",
    place: "02-784-8950",
    phone: "",
    email: "mentshin@naver.com",
    blog: "mentshin.com",
    twitter: "twitter.com/mentshin",
    facebook: "facebook.com/mentshin"
}, {
    id: 139,
    name: "신동근",
    party: 1,
    borough: "인천 서구을",
    dong: "검단1동, 검단2동, 검단3동, 검단4동, 검단5동, 검암경서동, 연희동",
    place: "",
    phone: "02-784-6142",
    email: "sdkwin16@gmail.com",
    blog: "shindk.kr",
    twitter: "twitter.com/skdc2875",
    facebook: "facebook.com/shindonggen?fref=ts"
}, {
    id: 140,
    name: "신보라",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관740호",
    phone: "02-784-8731",
    email: "qhepd111@naver.com",
    blog: "blog.naver.com/qhepd111",
    twitter: "",
    facebook: "facebook.com/qhfk111"
}, {
    id: 141,
    name: "신상진",
    party: 0,
    borough: "경기 성남시 중원구",
    dong: "금광1동, 금광2동, 도촌동, 상대원1동, 상대원2동, 상대원3동, 성남동, 은행1동, 은행2동, 중앙동, 하대원동",
    place: "의원회관522호",
    phone: "02-784-1860",
    email: "smedass2015@naver.com",
    blog: "ssj.or.kr",
    twitter: "",
    facebook: "facebook.com/smedass"
}, {
    id: 142,
    name: "신용현",
    party: 2,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-2620",
    email: "yhshin845@gmail.com",
    blog: "",
    twitter: "",
    facebook: ""
}, {
    id: 143,
    name: "신창현",
    party: 1,
    borough: "경기 의왕시 과천시",
    dong: "갈현동, 고천동, 과천동, 내손1동, 내손2동, 문원동, 별양동, 부곡동, 부림동, 오전동, 중앙동, 청계동",
    place: "",
    phone: "02-784-5285",
    email: "shinchanghyun@naver.com",
    blog: "blog.naver.com/shinchanghyun",
    twitter: "",
    facebook: "facebook.com/shinch.page"
}, {
    id: 144,
    name: "심상정",
    party: 3,
    borough: "경기 고양시갑",
    dong: "고양동, 관산동, 성사1동, 성사2동, 식사동, 원신동, 주교동, 화정1동, 화정2동, 흥도동",
    place: "",
    phone: "02-784-9530",
    email: "sangjungsim@hanmail.net",
    blog: "minsim.or.kr",
    twitter: "twitter.com/sangjungsim",
    facebook: "facebook.com/simsangjung"
}, {
    id: 145,
    name: "심재권",
    party: 1,
    borough: "서울 강동구을",
    dong: "둔촌제1동, 둔촌제2동, 성내제1동, 성내제2동, 성내제3동, 천호제1동, 천호제2동, 천호제3동",
    place: "",
    phone: "02-788-2485",
    email: "sjk7210@hanmail.net",
    blog: "blog.naver.com/shimjk815",
    twitter: "twitter.com/sjk0815",
    facebook: "facebook.com/jkshim0588"
}, {
    id: 146,
    name: "심재철",
    party: 0,
    borough: "경기 안양시 동안구을",
    dong: "갈산동, 귀인동, 범계동, 신촌동, 평안동, 평촌동, 호계1동, 호계2동, 호계3동",
    place: "",
    phone: "02-784-4164",
    email: "cleanshim@naver.com",
    blog: "cleanshim.com",
    twitter: "twitter.com/cleanshim",
    facebook: "facebook.com/cleanshim"
}, {
    id: 147,
    name: "안규백",
    party: 1,
    borough: "서울 동대문구갑",
    dong: "용신동, 이문제1동, 이문제2동, 제기동, 청량리동, 회기동, 휘경제1동, 휘경제2동",
    place: "",
    phone: "02-784-4181",
    email: "intoan429@gmail.com",
    blog: "safe100.or.kr",
    twitter: "",
    facebook: "facebook.com/AGBhope"
}, {
    id: 148,
    name: "안민석",
    party: 1,
    borough: "경기 오산시",
    dong: "남촌동, 대원동, 세마동, 신장동, 중앙동, 초평동",
    place: "",
    phone: "02-784-3877",
    email: "ams2273@daum.net",
    blog: "osan21.or.kr",
    twitter: "twitter.com/eduhimang",
    facebook: "facebook.com/osan21"
}, {
    id: 149,
    name: "안상수",
    party: 0,
    borough: "인천 중구 동구 강화군 옹진군",
    dong: "강화읍, 교동면, 금창동, 길상면, 내가면, 대청면, 덕적면, 도원동, 동인천동, 만석동, 백령면, 북도면, 북성동, 불은면, 삼산면, 서도면, 선원면, 송림1동, 송림2동, 송림3·5동, 송림4동, 송림6동, 송월동, 송해면, 송현1·2동, 송현3동, 신포동, 신흥동, 양도면, 양사면, 연안동, 연평면, 영종동, 영흥면, 용유동, 운서동, 율목동, 자월면, 하점면, 화도면, 화수1·화평동, 화수2동",
    place: "의원회관643호",
    phone: "02-784-2690",
    email: "ahnssoo@naver.com",
    blog: "blog.naver.com/ahnssoo1",
    twitter: "twitter.com/ahnssoo",
    facebook: "facebook.com/ahnssoo1"
}, {
    id: 150,
    name: "안철수",
    party: 2,
    borough: "서울 노원구병",
    dong: "상계1동, 상계2동, 상계3·4동, 상계5동, 상계8동, 상계9동, 상계10동",
    place: "",
    phone: "02-788-2204",
    email: "ahncs0518@naver.com",
    blog: "ahncs.kr",
    twitter: "twitter.com/cheolsoo0919",
    facebook: "facebook.com/ahncs111"
}, {
    id: 151,
    name: "안호영",
    party: 1,
    borough: "전북 완주군 진안군 무주군 장수군",
    dong: "경천면, 계남면, 계북면, 고산면, 구이면, 동상면, 동향면, 마령면, 무주읍, 무풍면, 백운면, 번암면, 봉동읍, 부귀면, 부남면, 비봉면, 산서면, 삼례읍, 상관면, 상전면, 설천면, 성수면, 소양면, 안성면, 안천면, 용담면, 용진읍, 운주면, 이서면, 장계면, 장수읍, 적상면, 정천면, 주천면, 진안읍, 천천면, 화산면",
    place: "",
    phone: "02-784-9751",
    email: "ahnho065@gmail.com",
    blog: "blog.naver.com/lawanhoyoung",
    twitter: "",
    facebook: "facebook.com/ahnho065"
}, {
    id: 152,
    name: "양승조",
    party: 1,
    borough: "충남 천안시병",
    dong: "광덕면, 신방동, 쌍용1동, 쌍용2동, 쌍용3동, 청룡동, 풍세면",
    place: "",
    phone: "02-784-2173",
    email: "YSJ@assembly.go.kr",
    blog: "ysj.or.kr",
    twitter: "twitter.com/yangsim012",
    facebook: "facebook.com/yangsim012"
}, {
    id: 153,
    name: "어기구",
    party: 1,
    borough: "충남 당진시",
    dong: "고대면, 당진1동, 당진2동, 당진3동, 대호지면, 면천면, 석문면, 송산면, 송악읍, 순성면, 신평면, 우강면, 정미면, 합덕읍",
    place: "",
    phone: "02-784-4360",
    email: "kiyku@naver.com",
    blog: "cafe.daum.net/ekkw2012",
    twitter: "",
    facebook: ""
}, {
    id: 154,
    name: "엄용수",
    party: 0,
    borough: "경남 밀양시 의령군 함안군 창녕군",
    dong: "가곡동, 가례면, 가야읍, 계성면, 고암면, 교동, 군북면, 궁류면, 길곡면, 낙서면, 남지읍, 내이동, 내일동, 단장면, 대산면, 대의면, 대지면, 대합면, 도천면, 무안면, 법수면, 봉수면, 부곡면, 부림면, 부북면, 산내면, 산외면, 산인면, 삼랑진읍, 삼문동, 상남면, 상동면, 성산면, 여항면, 영산면, 용덕면, 유곡면, 유어면, 의령읍, 이방면, 장마면, 정곡면, 지정면, 창녕읍, 청도면, 초동면, 칠곡면, 칠북면, 칠서면, 칠원읍, 하남읍, 함안면, 화정면",
    place: "의원회관621호",
    phone: "02-784-2316",
    email: "mypr3814@naver.com",
    blog: "umys.co.kr/",
    twitter: "",
    facebook: "facebook.com/miraeyongsoo"
}, {
    id: 155,
    name: "여상규",
    party: 0,
    borough: "경남 사천시 남해군 하동군",
    dong: "고전면, 고현면, 곤명면, 곤양면, 금남면, 금성면, 남면, 남양동, 남해읍, 동서금동, 동서동, 미조면, 벌용동, 북천면, 사남면, 사천읍, 삼동면, 상주면, 서면, 서포면, 선구동, 설천면, 악양면, 양보면, 옥종면, 용현면, 이동면, 적량면, 정동면, 진교면, 창선면, 청암면, 축동면, 하동읍, 향촌동, 화개면, 횡천면",
    place: "의원회관743호",
    phone: "02-784-1845",
    email: "yeosk@assembly.go.kr",
    blog: "sky21.co.kr",
    twitter: "twitter.com/sky435",
    facebook: "facebook.com/sky435"
}, {
    id: 156,
    name: "염동열",
    party: 0,
    borough: "강원 태백시 횡성군 영월군 평창군 정선군",
    dong: "갑천면, 강림면, 고한읍, 공근면, 구문소동, 김삿갓면, 남면, 남면, 대관령면, 대화면, 둔내면, 문곡소도동, 미탄면, 방림면, 봉평면, 북면, 북평면, 사북읍, 삼수동, 상동읍, 상장동, 서원면, 수주면, 신동읍, 안흥면, 여량면, 영월읍, 용평면, 우천면, 임계면, 장성동, 정선읍, 주천면, 중동면, 진부면, 철암동, 청일면, 평창읍, 한반도면, 화암면, 황연동, 황지동, 횡성읍",
    place: "의원회관807호",
    phone: "02-784-9820",
    email: "pretty6792@gmail.com",
    blog: "eideabank.co.kr",
    twitter: "twitter.com/DY_YEOM",
    facebook: "facebook.com/yeomdy"
}, {
    id: 157,
    name: "오세정",
    party: 2,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-9518",
    email: "osjoffice@naver.com",
    blog: "",
    twitter: "",
    facebook: "facebook.com/miraeyongsoo"
}, {
    id: 158,
    name: "오신환",
    party: 0,
    borough: "서울 관악구을",
    dong: "난곡동, 난향동, 대학동, 미성동, 삼성동, 서림동, 서원동, 신사동, 신원동, 조원동",
    place: "",
    phone: "02-784-5761",
    email: "arang301@naver.com",
    blog: "blog.naver.com/arang301",
    twitter: "twitter.com/arang301",
    facebook: "facebook.com/arang301"
}, {
    id: 159,
    name: "오영훈",
    party: 1,
    borough: "제주 제주시을",
    dong: "건입동, 구좌읍, 봉개동, 삼양동, 아라동, 우도면, 이도1동, 이도2동, 일도1동, 일도2동, 조천읍, 화북동",
    place: "",
    phone: "02-784-5621",
    email: "younghun3706@naver.com",
    blog: "blog.naver.com/younghun3706/",
    twitter: "",
    facebook: "facebook.com/younghun21"
}, {
    id: 160,
    name: "오제세",
    party: 1,
    borough: "충북 청주시 서원구",
    dong: "남이면, 모충동, 분평동, 사직1동, 사직2동, 사창동, 산남동, 성화·개신·죽림동, 수곡1동, 수곡2동, 현도면",
    place: "",
    phone: "02-788-2303",
    email: "ojs0126@naver.com",
    blog: "ojs.or.kr",
    twitter: "",
    facebook: "facebook.com/ojs0126"
}, {
    id: 161,
    name: "우상호",
    party: 1,
    borough: "서울 서대문구갑",
    dong: "북아현동, 신촌동, 연희동, 천연동, 충현동, 홍제제1동, 홍제제2동",
    place: "",
    phone: "02-784-3071",
    email: "wsh2016v@gmail.com",
    blog: "woosangho.net",
    twitter: "",
    facebook: "facebook.com/woosangho"
}, {
    id: 162,
    name: "우원식",
    party: 1,
    borough: "서울 노원구을",
    dong: "상계6·7동, 중계1동, 중계2·3동, 중계4동, 중계본동, 하계1동, 하계2동",
    place: "",
    phone: "02-784-3601",
    email: "reform1-1@hanmail.net",
    blog: "우원식.kr",
    twitter: "twitter.com/wonsikw",
    facebook: "facebook.com/wonsikw"
}, {
    id: 163,
    name: "원유철",
    party: 0,
    borough: "경기 평택시갑",
    dong: "서정동, 서탄면, 세교동, 송북동, 송탄동, 신장1동, 신장2동, 중앙동, 지산동, 진위면, 통복동",
    place: "의원회관648호",
    phone: "02-784-4441",
    email: "wonyoochul@daum.net",
    blog: "won21.or.kr",
    twitter: "twitter.com/won6767",
    facebook: "facebook.com/wantyou67"
}, {
    id: 164,
    name: "원혜영",
    party: 1,
    borough: "경기 부천시오정구",
    dong: "고강1동, 고강본동, 성곡동, 신흥동, 오정동, 원종1동, 원종2동",
    place: "",
    phone: "02-784-3106",
    email: "whywon21@daum.net",
    blog: "wonhyeyoung.or.kr",
    twitter: "twitter.com/wonhyeyoung",
    facebook: "facebook.com/whywon"
}, {
    id: 165,
    name: "위성곤",
    party: 1,
    borough: "제주 서귀포시",
    dong: "남원읍, 대륜동, 대정읍, 대천동, 동홍동, 서홍동, 성산읍, 송산동, 안덕면, 영천동, 예래동, 정방동, 중문동, 중앙동, 천지동, 표선면, 효돈동",
    place: "",
    phone: "02-784-6450",
    email: "wisg1128@hanmail.net",
    blog: "wishjeju.kr",
    twitter: "twitter.com/wisg1128",
    facebook: "facebook.com/wisg1128"
}, {
    id: 166,
    name: "유기준",
    party: 0,
    borough: "부산 서구동구",
    dong: "남부민제1동, 남부민제2동, 동대신제1동, 동대신제2동, 동대신제3동, 범일제1동, 범일제2동, 범일제5동, 부민동, 서대신제1동, 서대신제3동, 서대신제4동, 수정제1동, 수정제2동, 수정제4동, 수정제5동, 아미동, 암남동, 좌천동, 초량제1동, 초량제2동, 초량제3동, 초량제6동, 초장동, 충무동",
    place: "의원회관550호",
    phone: "02-788-2493",
    email: "piloyu@hanmail.net",
    blog: "seogu21c.com",
    twitter: "",
    facebook: "facebook.com/YOOKIJUNE"
}, {
    id: 167,
    name: "유동수",
    party: 1,
    borough: "인천 계양구갑",
    dong: "작전1동, 작전2동, 작전서운동, 효성1동, 효성2동",
    place: "",
    phone: "02-784-3543",
    email: "newds61@naver.com",
    blog: "유동수.com",
    twitter: "twitter.com/newds61",
    facebook: "facebook.com/newds2016"
}, {
    id: 168,
    name: "유민봉",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관1015호",
    phone: "02-784-2060",
    email: "mbyoo1015@naver.com",
    blog: "blog.naver.com/mbyoo1015",
    twitter: "",
    facebook: "facebook.com/mbyoo1015"
}, {
    id: 169,
    name: "유성엽",
    party: 2,
    borough: "전북 정읍시 고창군",
    dong: "감곡면, 고부면, 내장상동, 농소동, 덕천면, 북면, 산내면, 산외면, 상교동, 소성면, 수성동, 시기동, 신태인읍, 연지동, 영원면, 옹동면, 이평면, 입암면, 장명동, 정우면, 초산동, 칠보면, 태인면",
    place: "",
    phone: "02-788-2209",
    email: "yousuoy@hanmail.net",
    blog: "yajeong.or.kr",
    twitter: "twitter.com/ya_jeong",
    facebook: "facebook.com/yajeong"
}, {
    id: 170,
    name: "유승민",
    party: 0,
    borough: "대구 동구을",
    dong: "공산동, 도평동, 방촌동, 불로·봉무동, 안심1동, 안심2동, 안심3·4동, 해안동",
    place: "의원회관916호",
    phone: "02-784-1840",
    email: "ysm21com@naver.com",
    blog: "ysm21.com",
    twitter: "",
    facebook: "facebook.com/sminyoo"
}, {
    id: 171,
    name: "유승희",
    party: 1,
    borough: "서울 성북구갑",
    dong: "길음제1동, 돈암제2동, 동선동, 보문동, 삼선동, 성북동, 안암동, 정릉제1동, 정릉제2동, 정릉제3동, 정릉제4동",
    place: "",
    phone: "02-784-4091",
    email: "337ysh@naver.com",
    blog: "yoush.org/",
    twitter: "twitter.com/337ysh",
    facebook: "facebook.com/youseunghee"
}, {
    id: 172,
    name: "유은혜",
    party: 1,
    borough: "경기 고양시병",
    dong: "고봉동, 마두1동, 마두2동, 백석1동, 백석2동, 일산2동, 장항1동, 장항2동, 정발산동, 중산동, 풍산동",
    place: "",
    phone: "02-784-4291",
    email: "way2yoo@naver.com",
    blog: "blog.naver.com/way2yoo",
    twitter: "twitter.com/way2yoo",
    facebook: "facebook.com/way2yoo"
}, {
    id: 173,
    name: "유의동",
    party: 0,
    borough: "경기 평택시을",
    dong: "고덕면, 비전1동, 비전2동, 신평동, 안중읍, 오성면, 원평동, 청북면, 팽성읍, 포승읍, 현덕면",
    place: "의원회관947호",
    phone: "02-784-7351",
    email: "ptopen730@naver.com",
    blog: "yueuidong.com",
    twitter: "",
    facebook: "facebook.com/euidongyu"
}, {
    id: 174,
    name: "유재중",
    party: 0,
    borough: "부산 수영구",
    dong: "광안제1동, 광안제2동, 광안제3동, 광안제4동, 남천제1동, 남천제2동, 망미제1동, 망미제2동, 민락동, 수영동",
    place: "의원회관710호",
    phone: "02-784-6066",
    email: "yoo@na.go.kr",
    blog: "yjj21.co.kr",
    twitter: "twitter.com/Yoojaejung",
    facebook: "facebook.com/jaejungy"
}, {
    id: 175,
    name: "윤관석",
    party: 1,
    borough: "인천 남동구을",
    dong: "간석2동, 간석3동, 구월2동, 만수1동, 만수2동, 만수3동, 만수4동, 만수5동, 만수6동, 장수서창동",
    place: "",
    phone: "02-784-4380",
    email: "winneryks@naver.com",
    blog: "blog.daum.net/ysj2005",
    twitter: "twitter.com/yks0817",
    facebook: "facebook.com/ysj2005"
}, {
    id: 176,
    name: "윤상직",
    party: 0,
    borough: "부산 기장군",
    dong: "기장읍, 일광면, 장안읍, 정관읍, 철마면",
    place: "의원회관505호",
    phone: "02-784-8940",
    email: "gijangyoon@naver.com",
    blog: "blog.naver.com/gijangyoon",
    twitter: "twitter.com/victorysangick",
    facebook: "facebook.com/yoonsangjick"
}, {
    id: 177,
    name: "윤상현",
    party: 0,
    borough: "인천 남구을",
    dong: "관교동, 문학동, 숭의1·3동, 숭의2동, 숭의4동, 용현1·4동, 용현2동, 용현3동, 용현5동, 학익1동, 학익2동",
    place: "의원회관529호",
    phone: "02-788-2805",
    email: "shyoon@na.go.kr",
    blog: "shyoon.co.kr",
    twitter: "twitter.com/sanghyun_yoon",
    facebook: "facebook.com/yoonsanghyun1962"
}, {
    id: 178,
    name: "윤소하",
    party: 3,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-3080",
    email: "yunsoha20@naver.com",
    blog: "yunsoha.kr",
    twitter: "",
    facebook: "facebook.com/yunsoha"
}, {
    id: 179,
    name: "윤영석",
    party: 0,
    borough: "경남 양산시갑",
    dong: "강서동, 물금읍, 삼성동, 상북면, 원동면, 중앙동, 하북면",
    place: "의원회관438호",
    phone: "02-784-4861",
    email: "hangomy@assembly.go.kr",
    blog: "blog.naver.com/hangomy",
    twitter: "",
    facebook: "facebook.com/yyshangomy"
}, {
    id: 180,
    name: "윤영일",
    party: 2,
    borough: "전남 해남군 완도군 진도군",
    dong: "계곡면, 고군면, 고금면, 군내면, 군외면, 금당면, 금일읍, 노화읍, 마산면, 문내면, 보길면, 북일면, 북평면, 산이면, 삼산면, 생일면, 소안면, 송지면, 신지면, 약산면, 옥천면, 완도읍, 의신면, 임회면, 조도면, 지산면, 진도읍, 청산면, 해남읍, 현산면, 화산면, 화원면, 황산면",
    place: "",
    phone: "02-784-1571",
    email: "hwj335@hanmail.net",
    blog: "blog.naver.com/yiyoon0101",
    twitter: "twitter.com/yoon571104",
    facebook: "facebook.com/yoon571104"
}, {
    id: 181,
    name: "윤재옥",
    party: 0,
    borough: "대구 달서구을",
    dong: "도원동, 상인1동, 상인2동, 상인3동, 월성1동, 월성2동, 진천동",
    place: "의원회관917호",
    phone: "02-784-4871",
    email: "7882579@naver.com",
    blog: "yunjaeok.com",
    twitter: "twitter.com/yunjaeok",
    facebook: "facebook.com/yunjaeok"
}, {
    id: 182,
    name: "윤종오",
    party: 4,
    borough: "울산 북구",
    dong: "강동동, 농소1동, 농소2동, 농소3동, 송정동, 양정동, 염포동, 효문동",
    place: "",
    phone: "02-784-8630",
    email: "jongo212121@naver.com",
    blog: "jongo21.modoo.at/",
    twitter: "",
    facebook: "facebook.com/jongo21"
}, {
    id: 183,
    name: "윤종필",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-7141",
    email: "jpyoon605@naver.com",
    blog: "blog.naver.com/jpyoon605",
    twitter: "",
    facebook: "facebook.com/jpyoon605"
}, {
    id: 184,
    name: "윤한홍",
    party: 0,
    borough: "경남 창원시 마산회원구",
    dong: "구암1동, 구암2동, 내서읍, 봉암동, 석전1동, 석전2동, 양덕1동, 양덕2동, 합성1동, 합성2동, 회성동, 회원1동, 회원2동",
    place: "의원회관823호",
    phone: "02-784-2371",
    email: "uhh609@naver.com",
    blog: "blog.naver.com/uhh609",
    twitter: "",
    facebook: "facebook.com/uhh609"
}, {
    id: 185,
    name: "윤호중",
    party: 1,
    borough: "경기 구리시",
    dong: "갈매동, 교문1동, 교문2동, 동구동, 수택1동, 수택2동, 수택3동, 인창동",
    place: "",
    phone: "02-784-4961",
    email: "hjyun327@gmail.com",
    blog: "blog.naver.com/hjyun327",
    twitter: "twitter.com/dpcorea",
    facebook: "facebook.com/hojung.yun"
}, {
    id: 186,
    name: "윤후덕",
    party: 1,
    borough: "경기 파주시갑",
    dong: "광탄면, 교하동, 운정1동, 운정2동, 운정3동, 조리읍, 탄현면",
    place: "",
    phone: "02-788-2587",
    email: "yoons609@hanmail.net",
    blog: "pajulove.kr",
    twitter: "twitter.com/yoons609",
    facebook: "facebook.com/yoons609"
}, {
    id: 187,
    name: "이개호",
    party: 1,
    borough: "전남 담양군 함평군 영광군 장성군",
    dong: "고서면, 군남면, 군서면, 금성면, 나산면, 낙월면, 남면, 남면, 담양읍, 대덕면, 대동면, 대마면, 대전면, 동화면, 묘량면, 무정면, 백수읍, 법성면, 봉산면, 북이면, 북일면, 북하면, 불갑면, 삼계면, 삼서면, 서삼면, 손불면, 수북면, 신광면, 엄다면, 염산면, 영광읍, 용면, 월산면, 월야면, 장성읍, 진원면, 창평면, 학교면, 함평읍, 해보면, 홍농읍, 황룡면",
    place: "",
    phone: "02-784-2165",
    email: "7880291@naver.com",
    blog: "blog.naver.com/lgh59623",
    twitter: "",
    facebook: "facebook.com/LeeGaeHo"
}, {
    id: 188,
    name: "이군현",
    party: 0,
    borough: "경남 통영시 고성군",
    dong: "개천면, 거류면, 고성읍, 광도면, 구만면, 대가면, 도산면, 도천동, 동해면, 마암면, 명정동, 무전동, 미수동, 봉평동, 북신동, 사량면, 산양읍, 삼산면, 상리면, 영오면, 영현면, 욕지면, 용남면, 정량동, 중앙동, 하이면, 하일면, 한산면, 회화면",
    place: "",
    phone: "02-784-6327",
    email: "koonhyonlee@hanmail.net",
    blog: "leekh.kr",
    twitter: "twitter.com/koonhyon",
    facebook: "facebook.com/koonhyon"
}, {
    id: 189,
    name: "이동섭",
    party: 2,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-788-2005",
    email: "nowoncap@naver.com",
    blog: "blog.naver.com/nowoncap",
    twitter: "twitter.com/leedongsup",
    facebook: "facebook.com/dongsup.lee.9"
}, {
    id: 190,
    name: "이만희",
    party: 0,
    borough: "경북 영천시 청도군",
    dong: "각남면, 각북면, 고경면, 금천면, 금호읍, 남부동, 대창면, 동부동, 매전면, 북안면, 서부동, 신녕면, 완산동, 운문면, 이서면, 임고면, 자양면, 중앙동, 청도읍, 청통면, 풍각면, 화남면, 화북면, 화산면, 화양읍",
    place: "의원회관602호",
    phone: "02-784-5901",
    email: "yc20002@naver.com",
    blog: "blog.naver.com/yc20002",
    twitter: "twitter.com/yc20002",
    facebook: "facebook.com/yc20002"
}, {
    id: 191,
    name: "이명수",
    party: 0,
    borough: "충남 아산시갑",
    dong: "도고면, 선장면, 신창면, 온양1동, 온양2동, 온양3동, 온양4동, 온양5동, 온양6동",
    place: "의원회관422호",
    phone: "02-788-2891",
    email: "mslee3@assembly.go.kr",
    blog: "mslee.co.kr/",
    twitter: "twitter.com/asanworld",
    facebook: "facebook.com/asanpride"
}, {
    id: 192,
    name: "이상돈",
    party: 2,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-4750",
    email: "sdl1951@naver.com",
    blog: "blog.naver.com/sdl1951",
    twitter: "",
    facebook: ""
}, {
    id: 193,
    name: "이상민",
    party: 1,
    borough: "대전 유성구을",
    dong: "관평동, 구즉동, 노은2동, 노은3동, 신성동, 전민동",
    place: "",
    phone: "02-784-0924",
    email: "smlee@assembly.go.kr",
    blog: "smlee.kr",
    twitter: "twitter.com/esangmin",
    facebook: "facebook.com/esangmin"
}, {
    id: 194,
    name: "이석현",
    party: 1,
    borough: "경기 안양시 동안구갑",
    dong: "관양1동, 관양2동, 달안동, 부림동, 부흥동, 비산1동, 비산2동, 비산3동",
    place: "",
    phone: "02-784-1631",
    email: "esh337@hanmail.net",
    blog: "lsh4u.kr",
    twitter: "twitter.com/lsh4u",
    facebook: "facebook.com/lsh4u"
}, {
    id: 195,
    name: "이양수",
    party: 0,
    borough: "강원 속초시 고성군 양양군",
    dong: "간성읍, 강현면, 거진읍, 교동, 금호동, 노학동, 대포동, 동명동, 서면, 손양면, 양양읍, 영랑동, 조양동, 죽왕면, 청호동, 토성면, 현남면, 현내면, 현북면",
    place: "의원회관938호",
    phone: "02-784-8150",
    email: "2yangs6288@naver.com",
    blog: "",
    twitter: "",
    facebook: "facebook.com/2yangs6288"
}, {
    id: 196,
    name: "이언주",
    party: 1,
    borough: "경기 광명시을",
    dong: "소하1동, 소하2동, 철산3동, 하안1동, 하안2동, 하안3동, 하안4동, 학온동",
    place: "",
    phone: "02-784-6201",
    email: "k041036@naver.com",
    blog: "m.blog.naver.com/k041036",
    twitter: "twitter.com/unjulee",
    facebook: "facebook.com/leeuj72"
}, {
    id: 197,
    name: "이완영",
    party: 0,
    borough: "경북 고령군 성주군 칠곡군",
    dong: "가산면, 가천면, 개진면, 금수면, 기산면, 다산면, 대가면, 대가야읍, 덕곡면, 동명면, 벽진면, 북삼읍, 석적읍, 선남면, 성산면, 성주읍, 수륜면, 쌍림면, 약목면, 왜관읍, 용암면, 우곡면, 운수면, 월항면, 지천면, 초전면",
    place: "의원회관545호",
    phone: "02-784-6351",
    email: "yiwy5777@naver.com",
    blog: "leedandi.kr",
    twitter: "twitter.com/yiwy57",
    facebook: "facebook.com/wanyoung77"
}, {
    id: 198,
    name: "이용득",
    party: 1,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-1730",
    email: "ydlee429@gmail.com",
    blog: "ydlee429.wixsite.com/ydlee429",
    twitter: "twitter.com/ydlee03",
    facebook: "facebook.com/yongdeuk.lee.92"
}, {
    id: 199,
    name: "이용주",
    party: 2,
    borough: "전남 여수시갑",
    dong: "광림동, 국동, 남면, 대교동, 돌산읍, 동문동, 만덕동, 문수동, 미평동, 삼산면, 서강동, 여서동, 월호동, 중앙동, 충무동, 한려동",
    place: "",
    phone: "02-784-6090",
    email: "glyj532@gmail.com",
    blog: "",
    twitter: "",
    facebook: "facebook.com/profile.php?id=100009103596004"
}, {
    id: 200,
    name: "이용호",
    party: 2,
    borough: "전북 남원시 임실군 순창군",
    dong: "강진면, 관촌면, 구림면, 금과면, 금동, 금지면, 노암동, 대강면, 대산면, 덕과면, 덕치면, 도통동, 동계면, 동충동, 보절면, 복흥면, 사매면, 산내면, 산동면, 삼계면, 성수면, 송동면, 수지면, 순창읍, 신덕면, 신평면, 쌍치면, 아영면, 오수면, 왕정동, 운봉읍, 운암면, 유등면, 이백면, 인계면, 인월면, 임실읍, 적성면, 주생면, 주천면, 죽항동, 지사면, 청웅면, 팔덕면, 풍산면, 향교동",
    place: "",
    phone: "02-784-2570",
    email: "614lyh@naver.com",
    blog: "blog.naver.com/614lyh",
    twitter: "",
    facebook: "facebook.com/victoryyongho"
}, {
    id: 201,
    name: "이우현",
    party: 0,
    borough: "경기 용인시갑",
    dong: "남사면, 동부동, 모현면, 백암면, 양지면, 역삼동, 원삼면, 유림동, 이동면, 중앙동, 포곡읍",
    place: "의원회관443호",
    phone: "02-784-6441",
    email: "lwh99@hanmail.net",
    blog: "blog.naver.com/bravolwh",
    twitter: "twitter.com/lwh99_",
    facebook: "facebook.com/bravolwh"
}, {
    id: 202,
    name: "이원욱",
    party: 1,
    borough: "경기 화성시을",
    dong: "동탄1동, 동탄2동, 동탄3동, 동탄4동, 동탄면",
    place: "",
    phone: "02-784-6471",
    email: "ewon33@hanmail.net",
    blog: "blog.naver.com/ewon33",
    twitter: "twitter.com/ewon33",
    facebook: "facebook.com/ewon33"
}, {
    id: 203,
    name: "이은권",
    party: 0,
    borough: "대전 중구",
    dong: "대사동, 대흥동, 목동, 문창동, 문화1동, 문화2동, 부사동, 산성동, 석교동, 오류동, 용두동, 유천1동, 유천2동, 은행선화동, 중촌동, 태평1동, 태평2동",
    place: "의원회관538호",
    phone: "02-784-3457",
    email: "leeek1105@hanmail.net",
    blog: "bolg.naver.com/leeek1105",
    twitter: "twitter.com/leeeunkwon",
    facebook: "facebook.com/junggu1"
}, {
    id: 204,
    name: "이은재",
    party: 0,
    borough: "서울 강남구병",
    dong: "대치1동, 대치2동, 대치4동, 도곡1동, 도곡2동, 삼성1동, 삼성2동",
    place: "의원회관937호",
    phone: "02-784-1751",
    email: "lej@assembly.go.kr",
    blog: "blog.naver.com/eunjaelee_korea",
    twitter: "",
    facebook: ""
}, {
    id: 205,
    name: "이인영",
    party: 1,
    borough: "서울 구로구갑",
    dong: "개봉제1동, 개봉제2동, 개봉제3동, 고척제1동, 고척제2동, 수궁동, 오류제1동, 오류제2동",
    place: "",
    phone: "02-784-6811",
    email: "liy1964@empal.com",
    blog: "inyoung.net",
    twitter: "twitter.com/lee_inyoung",
    facebook: "facebook.com/bigbang1003"
}, {
    id: 206,
    name: "이장우",
    party: 0,
    borough: "대전 동구",
    dong: "가양1동, 가양2동, 대동, 대청동, 산내동, 삼성동, 성남동, 신인동, 용운동, 용전동, 자양동, 중앙동, 판암1동, 판암2동, 홍도동, 효동",
    place: "",
    phone: "02-784-6931",
    email: "jwoo2772@hanmail.net",
    blog: "blog.naver.com/jwoo37",
    twitter: "twitter.com/jangwoo2020",
    facebook: "facebook.com/jwoo37"
}, {
    id: 207,
    name: "이재정",
    party: 1,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-788-2619",
    email: "leejjlaw@gmail.com",
    blog: "blog.naver.com/leejjlaw",
    twitter: "",
    facebook: "facebook.com/leejjlaw"
}, {
    id: 208,
    name: "이정미",
    party: 3,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-4591",
    email: "justice55127@gmail.com",
    blog: "justice551.tistory.com",
    twitter: "twitter.com/jinbo27",
    facebook: "facebook.com/jinbo27"
}, {
    id: 209,
    name: "이정현",
    party: 0,
    borough: "전남 순천시",
    dong: "낙안면, 남제동, 덕연동, 도사동, 매곡동, 별량면, 삼산동, 상사면, 서면, 송광면, 승주읍, 왕조1동, 왕조2동, 외서면, 월등면, 장천동, 저전동, 조곡동, 주암면, 중앙동, 풍덕동, 해룡면, 향동, 황전면",
    place: "의원회관519호",
    phone: "",
    email: "jhlee519519@hanmail.net",
    blog: "이정현.com",
    twitter: "",
    facebook: "facebook.com/jhtoday58"
}, {
    id: 210,
    name: "이종걸",
    party: 1,
    borough: "경기 안양시 만안구",
    dong: "박달1동, 박달2동, 석수1동, 석수2동, 석수3동, 안양1동, 안양2동, 안양3동, 안양4동, 안양5동, 안양6동, 안양7동, 안양8동, 안양9동",
    place: "",
    phone: "02-788-2694",
    email: "anyang21@hanmail.net",
    blog: "ljk.co.kr",
    twitter: "twitter.com/leejongkul",
    facebook: "facebook.com/leejongkul"
}, {
    id: 211,
    name: "이종구",
    party: 0,
    borough: "서울 강남구갑",
    dong: "논현1동, 논현2동, 신사동, 압구정동, 역삼1동, 역삼2동, 청담동",
    place: "의원회관713호",
    phone: "02-784-3136",
    email: "jjongkoo50@naver.com",
    blog: "blog.naver.com/jjongkoo50/",
    twitter: "",
    facebook: "facebook.com/leejongkoo"
}, {
    id: 212,
    name: "이종명",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관337호",
    phone: "02-784-2174",
    email: "337leejm@hanmail.net",
    blog: "blog.naver.com/88leejm",
    twitter: "",
    facebook: "facebook.com/88leejm"
}, {
    id: 213,
    name: "이종배",
    party: 0,
    borough: "충북 충주시",
    dong: "교현2동, 교현·안림동, 금가면, 노은면, 달천동, 대소원면, 동량면, 목행·용탄동, 문화동, 봉방동, 산척면, 살미면, 성내·충인동, 소태면, 수안보면, 신니면, 앙성면, 엄정면, 연수동, 용산동, 주덕읍, 중앙탑면, 지현동, 칠금·금릉동, 호암·직동",
    place: "의원회관430호",
    phone: "02-784-4131",
    email: "victoryljb@naver.com",
    blog: "blog.naver.com/victorleejb",
    twitter: "twitter.com/leejongbae1026",
    facebook: ""
}, {
    id: 214,
    name: "이주영",
    party: 0,
    borough: "경남 창원시 마산합포구",
    dong: "가포동, 교방동, 구산면, 노산동, 동서동, 문화동, 반월동, 산호동, 성호동, 오동동, 완월동, 월영동, 자산동, 중앙동, 진동면, 진북면, 진전면, 합포동, 현동",
    place: "의원회관819호",
    phone: "02-784-5283",
    email: "newmasan@assembly.go.kr",
    blog: "newmasan.com",
    twitter: "twitter.com/newmasan",
    facebook: "facebook.com/newmasan315"
}, {
    id: 215,
    name: "이진복",
    party: 0,
    borough: "부산 동래구",
    dong: "명륜동, 명장제1동, 명장제2동, 복산동, 사직제1동, 사직제2동, 사직제3동, 수민동, 안락제1동, 안락제2동, 온천제1동, 온천제2동, 온천제3동",
    place: "의원회관449호",
    phone: "02-784-4316",
    email: "jinbok57@na.go.kr",
    blog: "leejinbok.co.kr/",
    twitter: "",
    facebook: "facebook.com/leejinbok57"
}, {
    id: 216,
    name: "이찬열",
    party: 4,
    borough: "경기 수원시갑",
    dong: "송죽동, 연무동, 영화동, 정자1동, 정자2동, 정자3동, 조원1동, 조원2동, 파장동",
    place: "",
    phone: "02-788-2975",
    email: "leecy@assembly.go.kr",
    blog: "leecy.or.kr",
    twitter: "twitter.com/leecy_jangan",
    facebook: "facebook.com/2chan10"
}, {
    id: 217,
    name: "이채익",
    party: 0,
    borough: "울산 남구갑",
    dong: "무거동, 삼호동, 신정1동, 신정2동, 신정3동, 신정4동, 신정5동, 옥동",
    place: "의원회관434호",
    phone: "02-784-8011",
    email: "lci8572@naver.com",
    blog: "이채익.com",
    twitter: "twitter.com/lci8572",
    facebook: "facebook.com/cheik.lee"
}, {
    id: 218,
    name: "이철규",
    party: 0,
    borough: "강원 동해시 삼척시",
    dong: "가곡면, 교동, 근덕면, 남양동, 노곡면, 도계읍, 동호동, 망상동, 묵호동, 미로면, 발한동, 부곡동, 북삼동, 북평동, 삼화동, 성내동, 송정동, 신기면, 원덕읍, 정라동, 천곡동, 하장면",
    place: "의원회관835호",
    phone: "02-784-9811",
    email: "cglee7@naver.com",
    blog: "blog.naver.com/cglee7",
    twitter: "",
    facebook: ""
}, {
    id: 219,
    name: "이철우",
    party: 0,
    borough: "경북 김천시",
    dong: "감문면, 감천면, 개령면, 구성면, 남면, 농소면, 대곡동, 대덕면, 대신동, 대항면, 봉산면, 부항면, 아포읍, 양금동, 어모면, 율곡동, 자산동, 조마면, 증산면, 지례면, 지좌동, 평화남산동",
    place: "의원회관908호",
    phone: "02-788-2461",
    email: "lcw619@hanmail.net",
    blog: "leecw.pe.kr/",
    twitter: "twitter.com/CUagainLee",
    facebook: "facebook.com/CUagainlee"
}, {
    id: 220,
    name: "이철희",
    party: 1,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-5080",
    email: "assembly923@naver.com",
    blog: "blog.naver.com/assembly923",
    twitter: "twitter.com/assembly923",
    facebook: ""
}, {
    id: 221,
    name: "이춘석",
    party: 1,
    borough: "전북 익산시갑",
    dong: "남중동, 마동, 모현동, 성당면, 송학동, 신동, 오산면, 용동면, 용안면, 웅포면, 인화동, 중앙동, 평화동, 함라면, 함열읍, 황등면",
    place: "",
    phone: "02-784-3285",
    email: "csa2418@naver.com",
    blog: "ebyon.com",
    twitter: "twitter.com/lcs1747",
    facebook: "facebook.com/chunseog.i"
}, {
    id: 222,
    name: "이태규",
    party: 2,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-8101",
    email: "ltk635@gmail.com",
    blog: "ltk2016635.blog.me",
    twitter: "",
    facebook: "facebook.com/leetkgo"
}, {
    id: 223,
    name: "이학영",
    party: 1,
    borough: "경기 군포시을",
    dong: "광정동, 궁내동, 산본2동, 수리동, 오금동, 재궁동",
    place: "",
    phone: "02-784-8051",
    email: "youngcamp1@gmail.com",
    blog: "ofthepeople.kr",
    twitter: "twitter.com/hackyoung1",
    facebook: "facebook.com/hackyoung"
}, {
    id: 224,
    name: "이학재",
    party: 0,
    borough: "인천 서구갑",
    dong: "가정1동, 가정2동, 가정3동, 가좌1동, 가좌2동, 가좌3동, 가좌4동, 석남1동, 석남2동, 석남3동, 신현원창동, 청라1동, 청라2동",
    place: "의원회관552호",
    phone: "02-784-1884",
    email: "hjv6465@assembly.go.kr",
    blog: "leehj.net",
    twitter: "twitter.com/hjv6465",
    facebook: "facebook.com/hjv6465"
}, {
    id: 225,
    name: "이해찬",
    party: 1,
    borough: "세종 세종",
    dong: "금남면, 도담동, 부강면, 소정면, 아름동, 연기면, 연동면, 연서면, 장군면, 전동면, 전의면, 조치원읍, 한솔동",
    place: "",
    phone: "02-784-7901",
    email: "lhc21net@gmail.com",
    blog: "hopechan.kr",
    twitter: "twitter.com/lhc21net",
    facebook: "facebook.com/lhc21net"
}, {
    id: 226,
    name: "이헌승",
    party: 0,
    borough: "부산 부산진구을",
    dong: "가야제1동, 가야제2동, 개금제1동, 개금제2동, 개금제3동, 범천제1동, 범천제2동, 부전제2동, 전포제1동, 전포제2동",
    place: "의원회관425호",
    phone: "02-784-7911",
    email: "ilovebusanjin@hanmail.net",
    blog: "ilovebusanjin.com",
    twitter: "twitter.com/g7member",
    facebook: "facebook.com/ilovebusanjin"
}, {
    id: 227,
    name: "이현재",
    party: 0,
    borough: "경기 하남시",
    dong: "감북동, 덕풍1동, 덕풍2동, 덕풍3동, 미사1동, 미사2동, 신장1동, 신장2동, 위례동, 천현동, 초이동, 춘궁동, 풍산동",
    place: "의원회관432호",
    phone: "02-784-8071",
    email: "hanam432@naver.com",
    blog: "lhj21.com",
    twitter: "twitter.com/hannaralhj",
    facebook: "facebook.com/hannaralhj"
}, {
    id: 228,
    name: "이혜훈",
    party: 0,
    borough: "서울 서초구갑",
    dong: "반포1동, 반포2동, 반포3동, 반포4동, 반포본동, 방배1동, 방배4동, 방배본동, 잠원동",
    place: "의원회관914호",
    phone: "02-784-4467",
    email: "leehyehoon@naver.com",
    blog: "leehyehoon.kr/",
    twitter: "",
    facebook: "facebook.com/hyehoon.lee.7"
}, {
    id: 229,
    name: "이훈",
    party: 1,
    borough: "서울 금천구",
    dong: "가산동, 독산제1동, 독산제2동, 독산제3동, 독산제4동, 시흥제1동, 시흥제2동, 시흥제3동, 시흥제4동, 시흥제5동",
    place: "",
    phone: "02-784-8430",
    email: "woogyoo@naver.com",
    blog: "blog.naver.com/woogyoo",
    twitter: "",
    facebook: "facebook.com/hooney4us"
}, {
    id: 230,
    name: "인재근",
    party: 1,
    borough: "서울 도봉구갑",
    dong: "쌍문1동, 쌍문3동, 창1동, 창2동, 창3동, 창4동, 창5동",
    place: "",
    phone: "02-784-8091",
    email: "ijgalso@daum.net",
    blog: "ijk.or.kr",
    twitter: "twitter.com/JGT_FOREVER",
    facebook: "facebook.com/ijk2012"
}, {
    id: 231,
    name: "임이자",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관747호",
    phone: "02-784-6970",
    email: "llj11@hanmail.net",
    blog: "blog.naver.com/llj11",
    twitter: "",
    facebook: ""
}, {
    id: 232,
    name: "임종성",
    party: 1,
    borough: "경기 광주시을",
    dong: "곤지암읍, 도척면, 오포읍, 초월읍",
    place: "",
    phone: "02-784-8380",
    email: "ijs5321@naver.com",
    blog: "blog.naver.com/ijs5321",
    twitter: "twitter.com/5321tempia",
    facebook: "facebook.com/ijs5321"
}, {
    id: 233,
    name: "장병완",
    party: 2,
    borough: "광주 동구남구갑",
    dong: "대촌동, 봉선1동, 봉선2동, 송암동, 월산4동, 월산5동, 월산동, 주월1동, 주월2동, 효덕동",
    place: "",
    phone: "02-784-5270",
    email: "cbwhope@naver.com",
    blog: "cbwhope.or.kr",
    twitter: "twitter.com/cbwhope",
    facebook: "facebook.com/ChangByoungWan"
}, {
    id: 234,
    name: "장석춘",
    party: 0,
    borough: "경북 구미시을",
    dong: "고아읍, 도개면, 무을면, 산동면, 선산읍, 양포동, 옥성면, 인동동, 장천면, 진미동, 해평면",
    place: "의원회관637호",
    phone: "02-784-7380",
    email: "jsc5708@hanmail.net",
    blog: "blog.naver.com/firstgumi",
    twitter: "",
    facebook: "facebook.com/jangseokchoon"
}, {
    id: 235,
    name: "장정숙",
    party: 2,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-1530",
    email: "assemblyjjs@naver.com",
    blog: "blog.naver.com/assemblyjjs",
    twitter: "",
    facebook: "facebook.com/assemblyjjs"
}, {
    id: 236,
    name: "장제원",
    party: 0,
    borough: "부산 사상구",
    dong: "감전동, 괘법동, 덕포제1동, 덕포제2동, 모라제1동, 모라제3동, 삼락동, 엄궁동, 주례제1동, 주례제2동, 주례제3동, 학장동",
    place: "의원회관514호",
    phone: "02-784-3851",
    email: "feelike0413@naver.com",
    blog: "jfirst21.com/kor/index.php",
    twitter: "twitter.com/changjewon",
    facebook: "facebook.com/bravojewon"
}, {
    id: 237,
    name: "전재수",
    party: 1,
    borough: "부산 북구 강서구갑",
    dong: "구포제1동, 구포제2동, 구포제3동, 덕천제1동, 덕천제2동, 덕천제3동, 만덕제1동, 만덕제2동, 만덕제3동",
    place: "",
    phone: "02-784-7431",
    email: "jsstory7@naver.com",
    blog: "blog.naver.com/jsstory7",
    twitter: "twitter.com/niceJaesoo",
    facebook: "facebook.com/niceJaesoo"
}, {
    id: 238,
    name: "전해철",
    party: 1,
    borough: "경기 안산시 상록구갑",
    dong: "반월동, 본오1동, 본오2동, 본오3동, 사1동, 사2동, 사3동",
    place: "",
    phone: "02-784-8901",
    email: "sangrokgab@naver.com",
    blog: "blog.naver.com/jhc05",
    twitter: "twitter.com/HaeC_J",
    facebook: "facebook.com/HaecheorJeon"
}, {
    id: 239,
    name: "전현희",
    party: 1,
    borough: "서울 강남구을",
    dong: "개포1동, 개포2동, 개포4동, 세곡동, 수서동, 일원1동, 일원2동, 일원본동",
    place: "",
    phone: "02-784-6950",
    email: "elysiaj@naver.com",
    blog: "blog.naver.com/elysiaj",
    twitter: "twitter.com/hyunheejeon",
    facebook: "facebook.com/okjeonhyunhyi"
}, {
    id: 240,
    name: "전혜숙",
    party: 1,
    borough: "서울 광진구갑",
    dong: "광장동, 구의제2동, 군자동, 능동, 중곡제1동, 중곡제2동, 중곡제3동, 중곡제4동",
    place: "",
    phone: "02-784-8340",
    email: "jhsook7612@naver.com",
    blog: "jun-hs.com/",
    twitter: "",
    facebook: "facebook.com/winner1219"
}, {
    id: 241,
    name: "전희경",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관629호",
    phone: "02-784-4630",
    email: "liberty_20@naver.com",
    blog: "blog.naver.com/liberty_20",
    twitter: "",
    facebook: "facebook.com/profile.php?id=100006411270507&fref=ts"
}, {
    id: 242,
    name: "정갑윤",
    party: 0,
    borough: "울산 중구",
    dong: "다운동, 반구1동, 반구2동, 병영1동, 병영2동, 복산1동, 복산2동, 성안동, 약사동, 우정동, 중앙동, 태화동, 학성동",
    place: "의원회관1006호",
    phone: "02-784-5275",
    email: "mrjung@assembly.go.kr",
    blog: "mrjung.net",
    twitter: "",
    facebook: "facebook.com/mrjung2"
}, {
    id: 243,
    name: "정동영",
    party: 2,
    borough: "전북 전주시병",
    dong: "금암1동, 금암2동, 덕진동, 동산동, 송천1동, 송천2동, 우아1동, 우아2동, 인후1동, 인후2동, 조촌동, 진북동, 팔복동, 호성동",
    place: "",
    phone: "02-784-9540",
    email: "cdy@cdy21.net",
    blog: "cdy21.net/",
    twitter: "twitter.com/coreacdy",
    facebook: "facebook.com/coreacdy"
}, {
    id: 244,
    name: "정병국",
    party: 0,
    borough: "경기 여주시 양평군",
    dong: "가남읍, 강상면, 강천면, 강하면, 개군면, 금사면, 능서면, 단월면, 대신면, 북내면, 산북면, 서종면, 양동면, 양서면, 양평읍, 여흥동, 오학동, 옥천면, 용문면, 점동면, 중앙동, 지평면, 청운면, 흥천면",
    place: "의원회관801호",
    phone: "02-788-2210",
    email: "bgchoung@assembly.go.kr",
    blog: "byounggug.co.kr",
    twitter: "twitter.com/withbg",
    facebook: "facebook.com/withbg"
}, {
    id: 245,
    name: "정성호",
    party: 1,
    borough: "경기 양주시",
    dong: "광적면, 남면, 백석읍, 양주1동, 양주2동, 은현면, 장흥면, 회천1동, 회천2동, 회천3동, 회천4동",
    place: "",
    phone: "02-784-8991",
    email: "jsh35351@naver.com",
    blog: "jungsh.co.kr",
    twitter: "",
    facebook: "facebook.com/JungSungho1"
}, {
    id: 246,
    name: "정세균",
    party: 4,
    borough: "서울 종로구",
    dong: "가회동, 교남동, 무악동, 부암동, 사직동, 삼청동, 숭인제1동, 숭인제2동, 이화동, 종로1·2·3·4가동, 종로5·6가동, 창신제1동, 창신제2동, 창신제3동, 청운효자동, 평창동, 혜화동",
    place: "",
    phone: "02-788-2895",
    email: "skchung@assembly.go.kr",
    blog: "skchung.or.kr",
    twitter: "twitter.com/sk0926",
    facebook: "facebook.com/peopleinside2012"
}, {
    id: 247,
    name: "정양석",
    party: 0,
    borough: "서울 강북구갑",
    dong: "번제1동, 번제2동, 수유제1동, 수유제2동, 수유제3동, 우이동, 인수동",
    place: "의원회관520호",
    phone: "02-784-5260",
    email: "cys9904@gmail.com",
    blog: "blog.naver.com/wjddidtjr4u",
    twitter: "twitter.com/okcys",
    facebook: "facebook.com/okcys"
}, {
    id: 248,
    name: "정용기",
    party: 0,
    borough: "대전 대덕구",
    dong: "대화동, 덕암동, 목상동, 법1동, 법2동, 비래동, 석봉동, 송촌동, 신탄진동, 오정동, 중리동, 회덕동",
    place: "의원회관647호",
    phone: "02-784-7190",
    email: "jbrave119@naver.com",
    blog: "blog.naver.com/jbrave119",
    twitter: "twitter.com/jbrave119",
    facebook: "facebook.com/jbrave119"
}, {
    id: 249,
    name: "정우택",
    party: 0,
    borough: "충북 청주시 상당구",
    dong: "가덕면, 금천동, 남일면, 낭성면, 문의면, 미원면, 성안동, 영운동, 용담·명암·산성동, 용암제1동, 용암제2동, 중앙동, 탑·대성동",
    place: "의원회관846호",
    phone: "02-784-9071",
    email: "wtc218@gmail.com",
    blog: "wtc21.co.kr",
    twitter: "twitter.com/bigwtc",
    facebook: "facebook.com/bigwtc"
}, {
    id: 250,
    name: "정운천",
    party: 0,
    borough: "전북 전주시을",
    dong: "삼천1동, 삼천2동, 삼천3동, 서신동, 효자1동, 효자2동, 효자3동, 효자4동",
    place: "",
    phone: "02-784-8975",
    email: "gbs2008@daum.net",
    blog: "blog.naver.com/jeonjujeong",
    twitter: "twitter.com/gbs2008",
    facebook: "facebook.com/gbs2008"
}, {
    id: 251,
    name: "정유섭",
    party: 0,
    borough: "인천 부평구갑",
    dong: "부개1동, 부평1동, 부평2동, 부평3동, 부평4동, 부평5동, 부평6동, 산곡3동, 산곡4동, 십정1동, 십정2동, 일신동",
    place: "의원회관339호",
    phone: "02-784-9423",
    email: "jungmomaf@naver.com",
    blog: "blog.naver.com/jungmomaf",
    twitter: "",
    facebook: "facebook.com/jungyousub"
}, {
    id: 252,
    name: "정인화",
    party: 2,
    borough: "전남 광양시 곡성군 구례군",
    dong: "간전면, 겸면, 고달면, 곡성읍, 골약동, 광양읍, 광영동, 광의면, 구례읍, 금호동, 다압면, 마산면, 목사동면, 문척면, 봉강면, 산동면, 삼기면, 석곡면, 오곡면, 오산면, 옥곡면, 옥과면, 옥룡면, 용방면, 입면, 죽곡면, 중마동, 진상면, 진월면, 태인동, 토지면",
    place: "",
    phone: "02-784-3770",
    email: "101bbb@naver.com",
    blog: "blog.naver.com/101bbb",
    twitter: "",
    facebook: "facebook.com/profile.php?id=100003671842964"
}, {
    id: 253,
    name: "정재호",
    party: 1,
    borough: "경기 고양시을",
    dong: "능곡동, 대덕동, 신도동, 창릉동, 행신1동, 행신2동, 행신3동, 행주동, 화전동, 효자동",
    place: "",
    phone: "02-784-0712",
    email: "nice929ho@gmail.com",
    blog: "nice929ho.kr",
    twitter: "twitter.com/2wa5",
    facebook: "facebook.com/2wa5.jjh"
}, {
    id: 254,
    name: "정종섭",
    party: 0,
    borough: "대구 동구갑",
    dong: "동촌동, 신암1동, 신암2동, 신암3동, 신암4동, 신암5동, 신천1·2동, 신천3동, 신천4동, 지저동, 효목1동, 효목2동",
    place: "의원회관1016호",
    phone: "02-784-6513",
    email: "chongjs57@naver.com",
    blog: "js2030.kr/",
    twitter: "",
    facebook: "facebook.com/jschong57"
}, {
    id: 255,
    name: "정진석",
    party: 0,
    borough: "충남 공주시 부여군 청양군",
    dong: "계룡면, 구룡면, 규암면, 금학동, 남면, 남양면, 내산면, 대치면, 목면, 반포면, 부여읍, 비봉면, 사곡면, 석성면, 세도면, 신관동, 신풍면, 양화면, 옥룡동, 옥산면, 외산면, 우성면, 운곡면, 웅진동, 월송동, 유구읍, 은산면, 의당면, 이인면, 임천면, 장암면, 장평면, 정산면, 정안면, 중학동, 청남면, 청양읍, 초촌면, 충화면, 탄천면, 홍산면, 화성면",
    place: "의원회관946호",
    phone: "02-784-5070",
    email: "chungjinsuk@naver.com",
    blog: "blog.naver.com/chungjinsuk",
    twitter: "twitter.com/js0904",
    facebook: "facebook.com/jinsukdream"
}, {
    id: 256,
    name: "정춘숙",
    party: 1,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-3740",
    email: "hopejung@na.go.kr",
    blog: "blog.naver.com/chounsook_jung",
    twitter: "",
    facebook: "facebook.com/chounsookjung"
}, {
    id: 257,
    name: "정태옥",
    party: 0,
    borough: "대구 북구갑",
    dong: "검단동, 고성동, 노원동, 대현동, 복현1동, 복현2동, 산격1동, 산격2동, 산격3동, 산격4동, 칠성동, 침산1동, 침산2동, 침산3동",
    place: "의원회관419호",
    phone: "02-784-2820",
    email: "okjtaeok@naver.com",
    blog: "blog.naver.com/okjtaeok",
    twitter: "twitter.com/jtaeok",
    facebook: "facebook.com/okjtaeok"
}, {
    id: 258,
    name: "제윤경",
    party: 1,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-7451",
    email: "freedebt553@gmail.com",
    blog: "freedebt553.tistory.com/",
    twitter: "twitter.com/gyurl",
    facebook: "facebook.com/freedebt553"
}, {
    id: 259,
    name: "조경태",
    party: 0,
    borough: "부산 사하구을",
    dong: "감천제1동, 감천제2동, 구평동, 다대제1동, 다대제2동, 신평제1동, 신평제2동, 장림제1동, 장림제2동",
    place: "의원회관636호",
    phone: "02-784-6380",
    email: "yeskt@ktclub.kr",
    blog: "ktclub.kr",
    twitter: "twitter.com/Choforce",
    facebook: "facebook.com/Choforce"
}, {
    id: 260,
    name: "조배숙",
    party: 2,
    borough: "전북 익산시을",
    dong: "금마면, 낭산면, 동산동, 망성면, 삼기면, 삼성동, 어양동, 여산면, 영등1동, 영등2동, 왕궁면, 춘포면, 팔봉동",
    place: "",
    phone: "02-784-6264",
    email: "victory_cho@naver.com",
    blog: "blog.naver.com/victory_cho",
    twitter: "",
    facebook: "facebook.com/chobaesook"
}, {
    id: 261,
    name: "조승래",
    party: 1,
    borough: "대전 유성구갑",
    dong: "노은1동, 온천1동, 온천2동, 원신흥동, 진잠동",
    place: "",
    phone: "02-784-2640",
    email: "yuseong0413@daum.net",
    blog: "blog.naver.com/yuseong0413",
    twitter: "twitter.com/gasiri",
    facebook: "facebook.com/profile.php?id=1809560279"
}, {
    id: 262,
    name: "조원진",
    party: 0,
    borough: "대구 달서구병",
    dong: "감삼동, 두류1·2동, 두류3동, 본동, 본리동, 성당동, 송현1동, 송현2동",
    place: "의원회관1018호",
    phone: "02-788-2361",
    email: "cwj9900@daum.net / johj98@assembly.go.kr",
    blog: "chowonjin.com",
    twitter: "twitter.com/cho_wonjin",
    facebook: "facebook.com/chowonjin88"
}, {
    id: 263,
    name: "조응천",
    party: 1,
    borough: "경기 남양주시갑",
    dong: "수동면, 평내동, 호평동, 화도읍",
    place: "",
    phone: "02-784-2717",
    email: "chopros312@gmail.com",
    blog: "blog.naver.com/chopros",
    twitter: "twitter.com/chopros",
    facebook: "facebook.com/chopros"
}, {
    id: 264,
    name: "조정식",
    party: 1,
    borough: "경기 시흥시을",
    dong: "군자동, 월곶동, 정왕1동, 정왕2동, 정왕3동, 정왕4동, 정왕본동",
    place: "",
    phone: "02-788-2923",
    email: "7842760@naver.com",
    blog: "cjs.or.kr",
    twitter: "twitter.com/chojs21",
    facebook: "facebook.com/chojs21"
}, {
    id: 265,
    name: "조훈현",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관1009호",
    phone: "02-784-2187",
    email: "Chohoonhyun@assembly.go.kr",
    blog: "blog.naver.com/chohoonhyun",
    twitter: "",
    facebook: "facebook.com/chohoonhyun"
}, {
    id: 266,
    name: "주광덕",
    party: 0,
    borough: "경기 남양주시병",
    dong: "금곡동, 도농동, 양정동, 와부읍, 조안면, 지금동, 진건읍, 퇴계원면",
    place: "의원회관826호",
    phone: "02-784-2855",
    email: "jkd2311@naver.com",
    blog: "jkd21.modoo.at/",
    twitter: "",
    facebook: "facebook.com/jkd2311"
}, {
    id: 267,
    name: "주승용",
    party: 2,
    borough: "전남 여수시을",
    dong: "둔덕동, 묘도동, 삼일동, 소라면, 시전동, 쌍봉동, 여천동, 율촌면, 주삼동, 화양면, 화정면",
    place: "",
    phone: "02-788-2153",
    email: "joo350@hanmail.net",
    blog: "joo-sy.com",
    twitter: "twitter.com/joo350",
    facebook: "facebook.com/joo350"
}, {
    id: 268,
    name: "주호영",
    party: 0,
    borough: "대구 수성구을",
    dong: "두산동, 범물1동, 범물2동, 상동, 수성1가동, 수성2·3가동, 수성4가동, 중동, 지산1동, 지산2동, 파동",
    place: "의원회관607호",
    phone: "02-788-2137",
    email: "suseong@na.go.kr",
    blog: "joohoyoung.or.kr",
    twitter: "twitter.com/sangtoil",
    facebook: "facebook.com/sangtoil"
}, {
    id: 269,
    name: "지상욱",
    party: 0,
    borough: "서울 중구 성동구을",
    dong: "광희동, 금호1가동, 금호2·3가동, 금호4가동, 다산동, 동화동, 명동, 소공동, 신당동, 신당제5동, 약수동, 옥수동, 을지로동, 장충동, 중림동, 청구동, 필동, 황학동, 회현동",
    place: "의원회관420호",
    phone: "02-784-9640",
    email: "strenue@naver.com",
    blog: "blog.naver.com/strenue",
    twitter: "",
    facebook: "facebook.com/sangwuk.ji"
}, {
    id: 270,
    name: "진선미",
    party: 1,
    borough: "서울 강동구갑",
    dong: "강일동, 고덕제1동, 고덕제2동, 길동, 명일제1동, 명일제2동, 상일동, 암사제1동, 암사제2동, 암사제3동",
    place: "",
    phone: "02-784-9591",
    email: "smjingogo@naver.com",
    blog: "smjingogo.com",
    twitter: "twitter.com/sunmee_Jin",
    facebook: "facebook.com/smjingogo"
}, {
    id: 271,
    name: "진영",
    party: 1,
    borough: "서울 용산구",
    dong: "남영동, 보광동, 서빙고동, 용문동, 용산2가동, 원효로제1동, 원효로제2동, 이촌제1동, 이촌제2동, 이태원제1동, 이태원제2동, 청파동, 한강로동, 한남동, 효창동, 후암동",
    place: "",
    phone: "02-788-2925",
    email: "ychin21@assembly.go.kr",
    blog: "chinyoung.kr/",
    twitter: "",
    facebook: "facebook.com/ychin21"
}, {
    id: 272,
    name: "채이배",
    party: 2,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-9480",
    email: "cyber633@naver.com",
    blog: "doublechae.kr",
    twitter: "",
    facebook: "facebook.com/justin.chae.5"
}, {
    id: 273,
    name: "천정배",
    party: 2,
    borough: "광주 서구을",
    dong: "금호1동, 금호2동, 상무2동, 서창동, 풍암동, 화정3동, 화정4동",
    place: "",
    phone: "02-784-9850",
    email: "hope_1000@naver.com",
    blog: "hope_1000.blog.me",
    twitter: "",
    facebook: "facebook.com/jeongbaec"
}, {
    id: 274,
    name: "최경환",
    party: 0,
    borough: "경북 경산시",
    dong: "남부동, 남산면, 남천면, 동부동, 북부동, 서부1동, 서부2동, 압량면, 와촌면, 용성면, 자인면, 중방동, 중앙동, 진량읍, 하양읍",
    place: "의원회관746호",
    phone: "02-788-2458",
    email: "vision2015@assembly.go.kr",
    blog: "vision2015.com",
    twitter: "twitter.com/khwanchoi",
    facebook: "facebook.com/ckyunghwan"
}, {
    id: 275,
    name: "최경환",
    party: 2,
    borough: "광주 북구을",
    dong: "건국동, 동림동, 매곡동, 삼각동, 양산동, 용봉동, 운암1동, 운암2동, 운암3동, 일곡동",
    place: "",
    phone: "02-784-5891",
    email: "haeyumn@hanmail.net",
    blog: "blog.daum.net/beyondi",
    twitter: "twitter.com/choigyunghwan",
    facebook: "m.facebook.com/gyunghwan.choi"
}, {
    id: 276,
    name: "최교일",
    party: 0,
    borough: "경북 영주시 문경시 예천군",
    dong: "가은읍, 가흥1동, 가흥2동, 감천면, 개포면, 농암면, 단산면, 동로면, 마성면, 문경읍, 문수면, 보문면, 봉현면, 부석면, 산북면, 산양면, 상망동, 순흥면, 안정면, 영순면, 영주1동, 영주2동, 예천읍, 용궁면, 용문면, 유천면, 은풍면, 이산면, 장수면, 점촌1동, 점촌2동, 점촌3동, 점촌4동, 점촌5동, 지보면, 평은면, 풍기읍, 풍양면, 하망동, 호계면, 호명면, 효자면, 휴천1동, 휴천2동, 휴천3동",
    place: "의원회관934호",
    phone: "02-784-4195",
    email: "choi_gyoil@naver.com",
    blog: "blog.naver.com/choi_gyoil",
    twitter: "",
    facebook: "facebook.com/gyoil.choi"
}, {
    id: 277,
    name: "최도자",
    party: 2,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-8640",
    email: "cdj523@naver.com",
    blog: "choidoja.com",
    twitter: "twitter.com/choidoja",
    facebook: "facebook.com/profile.php?id=100013390290187"
}, {
    id: 278,
    name: "최명길",
    party: 1,
    borough: "서울 송파구을",
    dong: "가락1동, 문정2동, 삼전동, 석촌동, 잠실2동, 잠실3동, 잠실7동, 잠실본동",
    place: "",
    phone: "02-784-1307",
    email: "na836cmg@gmail.com",
    blog: "mk2017.blog.me/",
    twitter: "twitter.com/mgchoi2017",
    facebook: "facebook.com/myungghil86"
}, {
    id: 279,
    name: "최연혜",
    party: 0,
    borough: "비례대표",
    dong: "",
    place: "의원회관829호",
    phone: "02-784-5087",
    email: "choiyeonhye@na.go.kr",
    blog: "blog.naver.com/policy0829",
    twitter: "",
    facebook: "facebook.com/choiyeonhye"
}, {
    id: 280,
    name: "최운열",
    party: 1,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-2350",
    email: "wychoi2016@naver.com",
    blog: "blog.naver.com/wychoi2016",
    twitter: "",
    facebook: ""
}, {
    id: 281,
    name: "최인호",
    party: 1,
    borough: "부산 사하구갑",
    dong: "괴정제1동, 괴정제2동, 괴정제3동, 괴정제4동, 당리동, 하단제1동, 하단제2동",
    place: "",
    phone: "02-784-2195",
    email: "332inho@gmail.com",
    blog: "blog.naver.com/cih1966",
    twitter: "twitter.com/LoveSahagu",
    facebook: "facebook.com/LoveSaha"
}, {
    id: 282,
    name: "추경호",
    party: 0,
    borough: "대구 달성군",
    dong: "가창면, 구지면, 논공읍, 다사읍, 옥포면, 유가면, 하빈면, 현풍면, 화원읍",
    place: "의원회관328호",
    phone: "02-784-8946",
    email: "khchoo@assembly.go.kr",
    blog: "blog.naver.com/khchoo1224",
    twitter: "",
    facebook: "facebook.com/ChooKyungho"
}, {
    id: 283,
    name: "추미애",
    party: 1,
    borough: "서울 광진구을",
    dong: "구의제1동, 구의제3동, 자양제1동, 자양제2동, 자양제3동, 자양제4동, 화양동",
    place: "",
    phone: "02-784-1270",
    email: "choovision@naver.com",
    blog: "choomiae.com",
    twitter: "twitter.com/withchoomiae",
    facebook: "facebook.com/withchoomiae"
}, {
    id: 284,
    name: "추혜선",
    party: 3,
    borough: "비례대표",
    dong: "",
    place: "",
    phone: "02-784-9740",
    email: "choojustice@gmail.com",
    blog: "blog.naver.com/choojustice",
    twitter: "twitter.com/choojustice",
    facebook: "facebook.com/choojustice"
}, {
    id: 285,
    name: "표창원",
    party: 1,
    borough: "경기 용인시정",
    dong: "구성동, 동백동, 마북동, 보정동, 죽전1동, 죽전2동",
    place: "",
    phone: "02-784-9030",
    email: "pyogo413@naver.com",
    blog: "pyotal.site/",
    twitter: "twitter.com/drpyo",
    facebook: "facebook.com/cwpyo"
}, {
    id: 286,
    name: "하태경",
    party: 0,
    borough: "부산 해운대구갑",
    dong: "송정동, 우제1동, 우제2동, 우제3동, 좌제1동, 좌제2동, 좌제3동, 좌제4동, 중제1동, 중제2동",
    place: "의원회관939호",
    phone: "02-784-2491",
    email: "radiohaha@naver.com",
    blog: "radiohaha.net",
    twitter: "twitter.com/taekyungh",
    facebook: "facebook.com/radiohahapage"
}, {
    id: 287,
    name: "한선교",
    party: 0,
    borough: "경기 용인시병",
    dong: "동천동, 상현1동, 상현2동, 성복동, 신봉동, 풍덕천1동, 풍덕천2동",
    place: "의원회관913호",
    phone: "02-784-2066",
    email: "hansunkyo@assembly.go.kr",
    blog: "hansunkyo.com",
    twitter: "twitter.com/hansunkyo",
    facebook: "facebook.com/hansunkyo"
}, {
    id: 288,
    name: "한정애",
    party: 1,
    borough: "서울 강서구병",
    dong: "가양제3동, 등촌제1동, 등촌제2동, 염창동, 화곡본동, 화곡제4동, 화곡제6동",
    place: "",
    phone: "02-784-3051",
    email: "jeoung@gmail.com",
    blog: "한정애.com",
    twitter: "twitter.com/dudehowru",
    facebook: "facebook.com/jeongae.han"
}, {
    id: 289,
    name: "함진규",
    party: 0,
    borough: "경기 시흥시갑",
    dong: "과림동, 능곡동, 대야동, 매화동, 목감동, 신천동, 신현동, 연성동, 은행동, 장곡동",
    place: "의원회관547호",
    phone: "02-784-4277",
    email: "dreamham7@na.go.kr",
    blog: "dreamham7.co.kr",
    twitter: "",
    facebook: "facebook.com/dreamham7"
}, {
    id: 290,
    name: "홍문종",
    party: 0,
    borough: "경기 의정부시을",
    dong: "송산1동, 송산2동, 신곡1동, 신곡2동, 자금동, 장암동",
    place: "의원회관848호",
    phone: "02-784-4777",
    email: "mjhong830@naver.com",
    blog: "blog.naver.com/mjhong2004",
    twitter: "twitter.com/mjhong",
    facebook: "facebook.com/mjhong2004"
}, {
    id: 291,
    name: "홍문표",
    party: 0,
    borough: "충남 홍성군 예산군",
    dong: "갈산면, 결성면, 고덕면, 광시면, 광천읍, 구항면, 금마면, 대술면, 대흥면, 덕산면, 봉산면, 삽교읍, 서부면, 신암면, 신양면, 예산읍, 오가면, 은하면, 응봉면, 장곡면, 홍동면, 홍북면, 홍성읍",
    place: "의원회관336호",
    phone: "02-788-2954",
    email: "mphonglove@hanmail.net",
    blog: "mphong.com",
    twitter: "twitter.com/mphonglove",
    facebook: "facebook.com/munpyo.hong"
}, {
    id: 292,
    name: "홍영표",
    party: 1,
    borough: "인천 부평구을",
    dong: "갈산1동, 갈산2동, 부개2동, 부개3동, 산곡1동, 산곡2동, 삼산1동, 삼산2동, 청천1동, 청천2동",
    place: "",
    phone: "02-784-3143",
    email: "youngvote@hanmail.net",
    blog: "dreamyp.or.kr",
    twitter: "twitter.com/YoungpyoHong",
    facebook: "facebook.com/ypbupyeong"
}, {
    id: 293,
    name: "홍의락",
    party: 4,
    borough: "대구 북구을",
    dong: "관문동, 관음동, 구암동, 국우동, 동천동, 무태조야동, 읍내동, 태전1동, 태전2동",
    place: "",
    phone: "02-784-6277",
    email: "7882971@hanmail.net",
    blog: "blog.daum.net/tkrakrak",
    twitter: "twitter.com/rockysounds",
    facebook: "facebook.com/euirak.hong"
}, {
    id: 294,
    name: "홍익표",
    party: 1,
    borough: "서울 중구 성동구갑",
    dong: "마장동, 사근동, 성수1가제1동, 성수1가제2동, 성수2가제1동, 성수2가제3동, 송정동, 왕십리도선동, 왕십리제2동, 용답동, 응봉동, 행당제1동, 행당제2동",
    place: "",
    phone: "02-784-6887",
    email: "peace@peacehong.net",
    blog: "peacehong.net",
    twitter: "twitter.com/peace_hong",
    facebook: "facebook.com/peacehong"
}, {
    id: 295,
    name: "홍일표",
    party: 0,
    borough: "인천 남구갑",
    dong: "도화1동, 도화2·3동, 주안1동, 주안2동, 주안3동, 주안4동, 주안5동, 주안6동, 주안7동, 주안8동",
    place: "의원회관623호",
    phone: "02-784-6346",
    email: "hip@assembly.go.kr",
    blog: "hip.or.kr",
    twitter: "twitter.com/HongIP",
    facebook: "facebook.com/HONG.ILPYO"
}, {
    id: 296,
    name: "홍철호",
    party: 0,
    borough: "경기 김포시을",
    dong: "구래동, 김포2동, 대곶면, 양촌읍, 운양동, 월곶면, 통진읍, 하성면",
    place: "의원회관821호",
    phone: "02-784-5961",
    email: "victorygimpo@naver.com",
    blog: "ilovegimpo.org",
    twitter: "twitter.com/victorygimpo",
    facebook: "facebook.com/victorygimpo"
}, {
    id: 297,
    name: "황영철",
    party: 0,
    borough: "강원 홍천군 철원군 화천군 양구군 인제군",
    dong: "간동면, 갈말읍, 근남면, 근북면, 기린면, 김화읍, 남면, 남면, 남면, 내면, 내촌면, 동면, 동면, 동송읍, 두촌면, 방산면, 북면, 북방면, 사내면, 상남면, 상서면, 서면, 서면, 서석면, 서화면, 양구읍, 인제읍, 철원읍, 하남면, 해안면, 홍천읍, 화천읍, 화촌면",
    place: "의원회관618호",
    phone: "02-784-5707",
    email: "hhhyc@assembly.go.kr",
    blog: "blog.naver.com/hhhyc",
    twitter: "twitter.com/hhhyc",
    facebook: "facebook.com/hhhyc1"
}, {
    id: 298,
    name: "황주홍",
    party: 2,
    borough: "전남 고흥군 보성군 장흥군 강진군",
    dong: "강진읍, 겸백면, 고흥읍, 과역면, 관산읍, 군동면, 금산면, 남양면, 노동면, 대구면, 대덕읍, 대서면, 도덕면, 도암면, 도양읍, 도화면, 동강면, 동일면, 두원면, 득량면, 마량면, 문덕면, 미력면, 벌교읍, 병영면, 보성읍, 복내면, 봉래면, 부산면, 성전면, 신전면, 안양면, 영남면, 옴천면, 용산면, 웅치면, 유치면, 율어면, 작천면, 장동면, 장평면, 장흥읍, 점암면, 조성면, 칠량면, 포두면, 풍양면, 회진면, 회천면",
    place: "",
    phone: "02-784-8834",
    email: "pv21c@assembly.go.kr",
    blog: "hwangjuhong.com",
    twitter: "twitter.com/Hwangjuhong",
    facebook: "facebook.com/Hwangjuhong1"
}, {
    id: 299,
    name: "황희",
    party: 1,
    borough: "서울 양천구갑",
    dong: "목1동, 목2동, 목3동, 목4동, 목5동, 신정1동, 신정2동, 신정6동, 신정7동",
    place: "",
    phone: "02-784-8551",
    email: "hwanghee67@naver.com",
    blog: "blog.naver.com/hwanghee67",
    twitter: "",
    facebook: "facebook.com/sebhwang"
}];